/* Glossary: curated terms + every chapter flashcard term (deduplicated) */
(function () {
  const HF = window.HF;
  const terms = [
    ['Accounts payable (AP)', 'Amounts owed to suppliers for goods or services received on credit.'],
    ['Accounts receivable (AR)', 'Amounts customers owe the business for credit sales.'],
    ['Accrual', 'Recording revenue or expense in the period it is earned/incurred, before cash moves.'],
    ['Accumulated depreciation', 'Total depreciation charged on an asset to date; a contra-asset.'],
    ['Adjusted trial balance', 'Trial balance after adjusting entries; basis for financial statements.'],
    ['Adjusting entry', 'Period-end entry to record accruals, deferrals, depreciation and estimates.'],
    ['Aging schedule', 'Receivables or payables grouped by how long they have been outstanding.'],
    ['Amortisation', 'Allocation of the cost of an intangible asset over its useful life; also the gradual repayment of a loan.'],
    ['Analytic account', 'In Odoo, a tag/dimension (project, department, store) used to analyse costs and revenues.'],
    ['Anglo-Saxon accounting', 'Inventory method where COGS is recognised when the customer invoice is posted (common Odoo default in many localizations).'],
    ['Asset', 'A resource controlled by the entity as a result of past events, expected to provide future economic benefits.'],
    ['Audit trail', 'The chain of evidence linking reports back to entries and source documents; in Odoo also a log of changes.'],
    ['Bad debt', 'A receivable that will not be collected.'],
    ['Balance sheet', 'Statement of financial position at a point in time: assets, liabilities, equity.'],
    ['Bank reconciliation', 'Explaining differences between the bank statement and the cash book.'],
    ['Bank suspense account', 'In Odoo, temporary account holding bank statement lines until they are reconciled.'],
    ['Batch payment', 'Several payments grouped into one bank transfer or file.'],
    ['Bill of materials (BoM)', 'List of components and operations needed to make a product; used for product cost.'],
    ['Bonus issue', 'Free shares issued to shareholders by capitalising reserves.'],
    ['Book value', 'See carrying amount.'],
    ['Break-even point', 'Sales level where total revenue equals total costs; profit is zero.'],
    ['Budget', 'Financial plan for a future period.'],
    ['Capital expenditure (capex)', 'Spending on long-term assets that benefit future periods.'],
    ['Carrying amount', 'Asset cost less accumulated depreciation and impairment.'],
    ['Cash basis', 'Recording revenue and expenses only when cash is received or paid.'],
    ['Cash conversion cycle', 'DIO + DSO − DPO: days cash is tied up in operations.'],
    ['Chart of accounts', 'Structured list of all accounts used by an organisation.'],
    ['Closing entries', 'Entries that transfer temporary account balances to retained earnings/capital.'],
    ['Consolidation', 'Combining parent and subsidiaries into group financial statements.'],
    ['Contra account', 'An account that offsets a related account and has the opposite normal balance.'],
    ['Contribution margin', 'Selling price minus variable cost (per unit or in total).'],
    ['Cost of goods sold (COGS)', 'Cost of inventory sold during the period.'],
    ['Credit', 'The right side of an account.'],
    ['Credit note', 'Document reducing an amount owed by a customer (or to a supplier); reverses an invoice in whole or part.'],
    ['Current ratio', 'Current assets ÷ current liabilities.'],
    ['Cut-off', 'Recording transactions in the correct accounting period.'],
    ['Debit', 'The left side of an account.'],
    ['Deferred revenue', 'Cash received for goods/services not yet delivered; a liability (also unearned revenue).'],
    ['Deferred tax', 'Future tax consequences of temporary differences between accounting and tax bases.'],
    ['Depreciation', 'Systematic allocation of a tangible asset’s cost over its useful life.'],
    ['Dividend', 'Distribution of profits to shareholders.'],
    ['Double-entry bookkeeping', 'Every transaction is recorded with equal debits and credits in at least two accounts.'],
    ['Drawings', 'Amounts withdrawn by a sole trader/partner for personal use.'],
    ['DSO', 'Days sales outstanding: receivables ÷ revenue × 365.'],
    ['EBITDA', 'Earnings before interest, tax, depreciation and amortisation.'],
    ['Equity', 'Residual interest in assets after deducting liabilities.'],
    ['Equity method', 'Accounting for associates/JVs: cost plus share of profits less dividends.'],
    ['Expense', 'Decrease in economic benefits during the period that reduces equity (other than distributions).'],
    ['Exchange difference', 'Gain or loss from changes in foreign exchange rates.'],
    ['FIFO', 'First-in, first-out inventory cost formula.'],
    ['Financial statements', 'Income statement, balance sheet, statement of changes in equity, cash flow statement and notes.'],
    ['Fiscal position', 'Odoo rule set that maps taxes and accounts for certain partners (e.g., exports).'],
    ['Fiscal year', 'The 12-month accounting period a business reports on.'],
    ['Fixed cost', 'Cost that does not change with activity level in the short run.'],
    ['Free cash flow', 'Operating cash flow minus capital expenditure.'],
    ['GAAP', 'Generally Accepted Accounting Principles (often refers to US GAAP).'],
    ['General ledger', 'The complete set of accounts and their transactions.'],
    ['Going concern', 'Assumption the entity will continue operating for the foreseeable future.'],
    ['Goodwill', 'Excess of acquisition consideration (plus NCI) over fair value of identifiable net assets.'],
    ['Gross profit', 'Net revenue minus cost of goods sold.'],
    ['GST', 'Goods and Services Tax — a value-added tax used in India, Australia, Canada and others.'],
    ['IFRS', 'International Financial Reporting Standards, issued by the IASB.'],
    ['Impairment', 'Reduction of an asset’s carrying amount to its recoverable amount.'],
    ['Imprest system', 'Petty cash system with a fixed float replenished by the amount spent.'],
    ['Income statement', 'Report of revenue, expenses and profit for a period (P&L).'],
    ['Input tax', 'VAT/GST paid on purchases, usually reclaimable.'],
    ['Intangible asset', 'Identifiable non-physical asset: software, patents, licences, brands acquired.'],
    ['Internal control', 'Processes that provide reasonable assurance about reliable reporting, operations and compliance.'],
    ['Inventory', 'Goods held for sale, in production, or materials to be used in production.'],
    ['Journal', 'Chronological record of transactions; in Odoo also a container type (Sales, Purchase, Bank…).'],
    ['Journal entry', 'A record of a transaction with balanced debits and credits.'],
    ['Journal item', 'A single line of a journal entry (Odoo: account.move.line).'],
    ['Lease liability', 'Present value of lease payments not yet paid (IFRS 16).'],
    ['Ledger', 'Book or file of accounts showing all movements and balances.'],
    ['Liability', 'Present obligation to transfer an economic resource as a result of past events.'],
    ['LIFO', 'Last-in, first-out inventory method; prohibited under IFRS.'],
    ['Liquidity', 'Ability to meet short-term obligations.'],
    ['Lock date', 'A date before which journal entries cannot be added or changed.'],
    ['Matching principle', 'Recognise expenses in the same period as related revenues.'],
    ['Materiality', 'Information is material if omitting or misstating it could influence users’ decisions.'],
    ['Net realisable value (NRV)', 'Estimated selling price less costs to complete and sell.'],
    ['Non-controlling interest (NCI)', 'Equity in a subsidiary not attributable to the parent.'],
    ['Normal balance', 'The side (debit or credit) on which an account increases.'],
    ['Operating cycle', 'Time from buying inventory to collecting cash from customers.'],
    ['Other comprehensive income (OCI)', 'Gains and losses recognised outside profit, e.g., revaluation surplus.'],
    ['Outstanding receipts/payments account', 'Odoo account holding registered payments until matched with bank statement lines.'],
    ['Output tax', 'VAT/GST charged on sales; owed to the tax authority.'],
    ['Overhead', 'Indirect costs that cannot be traced directly to a product.'],
    ['Partner ledger', 'Odoo report of balances and movements per customer/vendor.'],
    ['Payment terms', 'Conditions defining when payment is due (and any early-payment discount).'],
    ['Petty cash', 'Small cash fund for minor expenses.'],
    ['Posting', 'Transferring journal entries to ledger accounts.'],
    ['Prepaid expense', 'Payment for future goods/services; an asset until consumed.'],
    ['Present value', 'Today’s value of future cash flows discounted at a rate.'],
    ['Provision', 'Liability of uncertain timing or amount.'],
    ['Purchase order (PO)', 'Document authorising a purchase from a supplier; no accounting entry by itself.'],
    ['Quick ratio', '(Cash + receivables + marketable securities) ÷ current liabilities.'],
    ['Reconciliation', 'Matching two sets of records to ensure they agree (bank, sub-ledgers, intercompany).'],
    ['Reconciliation model', 'Odoo rule/button that automates bank reconciliation counterparts or matching.'],
    ['Residual value', 'Estimated value of an asset at the end of its useful life.'],
    ['Retained earnings', 'Accumulated profits not distributed as dividends.'],
    ['Revenue', 'Income arising from ordinary activities.'],
    ['Reverse charge', 'Mechanism where the buyer accounts for VAT/GST instead of the seller.'],
    ['Reversing entry', 'Entry at the start of a period that reverses a prior-period accrual.'],
    ['Right-of-use asset', 'Lessee’s asset representing its right to use a leased asset.'],
    ['ROE', 'Return on equity: net profit ÷ average equity.'],
    ['Sales order', 'Confirmed customer order; no accounting entry until invoiced/delivered.'],
    ['Segregation of duties', 'Splitting custody, authorisation, recording and reconciliation between people.'],
    ['Source document', 'Evidence of a transaction (invoice, bill, receipt, statement).'],
    ['Standard cost', 'Predetermined cost per unit used for budgeting and variance analysis; also an Odoo costing method.'],
    ['Statement of cash flows', 'Report of cash inflows/outflows from operating, investing and financing activities.'],
    ['Statement of changes in equity', 'Reconciles opening and closing equity.'],
    ['Stock interim account', 'Odoo temporary account between stock moves and invoices/bills.'],
    ['Straight-line depreciation', '(Cost − residual value) ÷ useful life each year.'],
    ['Subsidiary ledger', 'Detailed ledger (customers, suppliers) supporting a control account.'],
    ['Sunk cost', 'A past cost that cannot be recovered; irrelevant for decisions.'],
    ['Suspense account', 'Temporary account for unexplained differences or unclassified items.'],
    ['T-account', 'Simple visual representation of an account with debit (left) and credit (right) sides.'],
    ['TDS / withholding tax', 'Tax deducted at source by the payer and remitted to the government.'],
    ['Temporary account', 'Revenue, expense and drawings/dividend accounts closed each period.'],
    ['Trial balance', 'List of ledger balances; total debits should equal total credits.'],
    ['Unearned revenue', 'See deferred revenue.'],
    ['Variable cost', 'Cost that changes in proportion to activity.'],
    ['Variance', 'Difference between actual and budgeted/standard amounts; favourable or adverse.'],
    ['VAT', 'Value Added Tax: consumption tax collected at each stage with input tax credits.'],
    ['Working capital', 'Current assets − current liabilities.'],
    ['Write-off', 'Removing an asset (e.g., an uncollectible receivable) from the books.'],
  ];
  const seen = new Set(terms.map((t) => t[0].toLowerCase()));
  HF.chapters.forEach((c) =>
    (c.cards || []).forEach(([f, b]) => {
      const k = f.toLowerCase();
      if (f.length < 48 && !f.includes('?') && !seen.has(k)) {
        seen.add(k);
        terms.push([f, b]);
      }
    })
  );
  HF.glossary = terms;
})();
