/* PART 2 — Financial Statements & the Close */
(function () {
  const HF = window.HF;
  HF.addPart({ id: 'p2', n: 2, title: 'Statements & the Close', color: '#2e86ab', badge: 'part2', desc: 'Accruals and adjusting entries, the income statement, balance sheet, cash flow statement and closing the books.' });

  /* =============================== CH 8 =============================== */
  HF.addChapter({
    id: 'accruals-adjustments',
    part: 'p2',
    title: 'Accruals & Adjusting Entries',
    subtitle: 'Why cash lies about profit — and how to make the books tell the truth',
    art: 'calendar',
    level: 'Intermediate',
    minutes: 30,
    quote: 'Cash tells you <i>when</i> money moved. Accrual accounting tells you <i>when the business actually earned it or used it up</i>.',
    goals: ['Contrast cash basis with accrual basis', 'Identify the four types of adjustments (prepaid, unearned, accrued expense, accrued revenue)', 'Record depreciation and estimate adjustments', 'Use reversing entries correctly'],
    blocks: [
      { t: 'h', text: 'Cash basis vs accrual basis' },
      { t: 'p', html: 'Under the <b>cash basis</b>, you record revenue when cash comes in and expenses when cash goes out. Simple — and misleading. Under the <b>accrual basis</b>, you record revenue when it’s <b>earned</b> and expenses when they’re <b>incurred</b>, no matter when cash moves. IFRS and US GAAP require accrual accounting for financial statements.' },
      { t: 'widget', name: 'accrual' },
      { t: 'brain', html: 'In the simulator, total quarter profit was the same under both methods <i>except</i> for the April prepayment. Why? What would happen if you looked at a much longer time span?' },

      { t: 'h', text: 'The four adjustment families' },
      { t: 'p', html: 'At period end, the timing of cash and the timing of the economic event often don’t line up. There are exactly four patterns — two <b>deferrals</b> (cash first, event later) and two <b>accruals</b> (event first, cash later):' },
      {
        t: 'cards',
        cols: 2,
        items: [
          { icon: '⏩💸', t: 'Prepaid expense (deferral)', d: 'You <b>paid</b> before using it: insurance, rent in advance, subscriptions. It’s an <b>asset</b> until used up.<br><i>Adjust:</i> Dr Expense / Cr Prepaid.', color: 'blue' },
          { icon: '⏩💰', t: 'Unearned revenue (deferral)', d: 'Customer <b>paid</b> before you delivered: deposits, gift cards, annual subscriptions. It’s a <b>liability</b> until earned.<br><i>Adjust:</i> Dr Unearned Revenue / Cr Revenue.', color: 'red' },
          { icon: '⏪💸', t: 'Accrued expense', d: 'You <b>used</b> it but haven’t been billed/paid: wages earned by staff, electricity, interest.<br><i>Adjust:</i> Dr Expense / Cr Accrued Liabilities.', color: 'yellow' },
          { icon: '⏪💰', t: 'Accrued revenue', d: 'You <b>earned</b> it but haven’t invoiced/collected: interest receivable, work done not yet billed.<br><i>Adjust:</i> Dr Accrued Revenue (asset) / Cr Revenue.', color: 'green' },
        ],
      },
      { t: 'sticky', html: 'Every adjusting entry touches <b>one balance sheet account</b> and <b>one income statement account</b>.<br>And it (almost) never touches <b>Cash</b>!' },

      { t: 'h3', text: '1. Prepaid expense' },
      { t: 'p', html: 'On 1 October, Max pays $1,200 for 12 months of shop insurance.' },
      { t: 'entry', date: 'Oct 1', lines: [['Prepaid Insurance', 1200, 0], ['Bank', 0, 1200]], narr: 'Paid 12 months insurance in advance' },
      { t: 'p', html: 'At 31 December (year-end), 3 months have been used: 3 × $100 = $300.' },
      { t: 'entry', date: 'Dec 31 — adjusting', lines: [['Insurance Expense', 300, 0], ['Prepaid Insurance', 0, 300]], narr: '3 months of insurance used' },
      { t: 'h3', text: '2. Unearned revenue' },
      { t: 'p', html: 'On 1 December, a cycling club pays $2,400 for 6 months of bike maintenance.' },
      { t: 'entry', date: 'Dec 1', lines: [['Bank', 2400, 0], ['Unearned Revenue', 0, 2400]], narr: 'Received 6 months maintenance in advance' },
      { t: 'entry', date: 'Dec 31 — adjusting', lines: [['Unearned Revenue', 400, 0], ['Service Revenue', 0, 400]], narr: '1 month of service delivered' },
      { t: 'h3', text: '3. Accrued expense' },
      { t: 'p', html: 'Staff are paid on the 5th of the following month. At 31 December they’ve earned $2,000 of December wages.' },
      { t: 'entry', date: 'Dec 31 — adjusting', lines: [['Wages Expense', 2000, 0], ['Wages Payable (Accrued)', 0, 2000]], narr: 'December wages earned, unpaid' },
      { t: 'h3', text: '4. Accrued revenue' },
      { t: 'p', html: 'Max lent $10,000 to a friend’s café at 6% p.a. on 1 October; interest is paid annually. By 31 December, 3 months’ interest has been earned: 10,000 × 6% × 3/12 = $150.' },
      { t: 'entry', date: 'Dec 31 — adjusting', lines: [['Interest Receivable', 150, 0], ['Interest Income', 0, 150]], narr: 'Interest earned, not yet received' },

      { t: 'widget', name: 'journal', opts: {
        id: 'ch8-adj',
        title: 'Adjusting entry gym',
        sub: 'Year-end is 31 December. Write the <b>adjusting entry</b> for each.',
        accounts: ['Bank', 'Prepaid Rent', 'Prepaid Insurance', 'Accounts Receivable', 'Accrued Revenue', 'Interest Receivable', 'Supplies', 'Accumulated Depreciation', 'Wages Payable', 'Accrued Liabilities', 'Interest Payable', 'Unearned Revenue', 'Service Revenue', 'Interest Income', 'Rent Expense', 'Insurance Expense', 'Supplies Expense', 'Wages Expense', 'Utilities Expense', 'Interest Expense', 'Depreciation Expense'],
        scenarios: [
          { text: 'On 1 Nov, paid 6 months rent of <b>$6,000</b> in advance (recorded as Prepaid Rent). Adjust at 31 Dec.', lines: [{ acct: 'Rent Expense', dr: 2000 }, { acct: 'Prepaid Rent', cr: 2000 }], why: '2 months used: 6,000 × 2/6 = 2,000.', hint: 'How many months of the six are used up?' },
          { text: 'Supplies account shows <b>$900</b>; a count finds <b>$250</b> still on hand.', lines: [{ acct: 'Supplies Expense', dr: 650 }, { acct: 'Supplies', cr: 650 }], why: 'Used = 900 − 250 = 650.' },
          { text: 'Electricity for December estimated at <b>$420</b>; the bill arrives in January.', lines: [{ acct: 'Utilities Expense', dr: 420 }, { acct: 'Accrued Liabilities', cr: 420 }], why: 'Accrued expense: incurred but not billed.' },
          { text: 'A customer prepaid <b>$3,000</b> for a 3-month service starting 1 Dec (recorded as Unearned Revenue).', lines: [{ acct: 'Unearned Revenue', dr: 1000 }, { acct: 'Service Revenue', cr: 1000 }], why: '1 of 3 months delivered.' },
          { text: 'Repairs worth <b>$800</b> were completed on 30 Dec but will only be invoiced in January.', lines: [{ acct: 'Accrued Revenue', dr: 800 }, { acct: 'Service Revenue', cr: 800 }], why: 'Earned → recognise revenue now. (Some use Accounts Receivable/unbilled receivables.)' },
          { text: 'Equipment depreciation for the year is <b>$3,600</b>.', lines: [{ acct: 'Depreciation Expense', dr: 3600 }, { acct: 'Accumulated Depreciation', cr: 3600 }], why: 'Depreciation spreads the asset’s cost over its life (Chapter 16).' },
          { text: 'A $20,000 loan at 9% p.a. was taken on 1 Sep; interest is paid annually on 31 Aug.', lines: [{ acct: 'Interest Expense', dr: 600 }, { acct: 'Interest Payable', cr: 600 }], why: '20,000 × 9% × 4/12 = 600 accrued.' },
        ],
      } },

      { t: 'h', text: 'Depreciation and estimates' },
      { t: 'p', html: 'Two other adjustments show up every period:' },
      {
        t: 'list',
        items: [
          '<b>Depreciation</b> — allocate the cost of long-lived assets across the years that benefit. Dr Depreciation Expense / Cr Accumulated Depreciation.',
          '<b>Estimates</b> — expected credit losses on receivables (bad debts), inventory write-downs, warranty provisions, bonuses. These are judgement calls; they must be reasonable and supportable.',
        ],
      },
      { t: 'watch', html: 'Adjustments are the <b>favourite playground for manipulation</b>: “forget” an accrual and profit looks higher; push revenue into this year and the bonus is safe. That’s why auditors spend so much time on cut-off and estimates.' },

      { t: 'h', text: 'Reversing entries' },
      { t: 'p', html: 'Optional but handy: on day 1 of the new period, reverse accruals. Then when the actual bill/payment comes, record it normally without worrying about splitting it.' },
      { t: 'entry', date: 'Jan 1 — reversing', lines: [['Wages Payable (Accrued)', 2000, 0], ['Wages Expense', 0, 2000]], narr: 'Reverse December wage accrual' },
      { t: 'entry', date: 'Jan 5 — payday', lines: [['Wages Expense', 2000, 0], ['Bank', 0, 2000]], narr: 'Paid December wages — the reversal makes January expense net to zero for this amount' },
      { t: 'odoo', title: 'Accruals & reversals in Odoo', html: 'Create a <b>Miscellaneous</b> journal entry and set an <b>Auto-reverse</b> date (or use the <b>Reverse</b> button) so Odoo posts the reversal on the first day of the next period. For prepaid/deferred items, Odoo 17+ can generate <b>deferred expense/revenue entries</b> automatically from a bill or invoice line with a start and end date (Chapter 30).' },
      {
        t: 'nodumb',
        qa: [
          ['Can small businesses use cash basis?', 'Many tax regimes allow small businesses to use cash accounting for tax purposes. But financial statements under IFRS/GAAP must be on an accrual basis, and accrual gives much better management information.'],
          ['Is an “accrual” the same as an “estimate”?', 'Not always. Some accruals are exact (interest on a loan). Others are estimates (electricity before the bill arrives). When the real number arrives, you adjust the difference.'],
          ['Why is unearned revenue a liability?', 'Because you owe the customer either the service or their money back. Until you deliver, it isn’t yours.'],
        ],
      },
      { t: 'bullets', items: ['Accrual basis: revenue when earned, expenses when incurred.', 'Deferrals: prepaid expenses (asset) and unearned revenue (liability).', 'Accruals: accrued expenses (liability) and accrued revenue (asset).', 'Adjusting entries hit one balance sheet and one P&L account — rarely cash.', 'Depreciation and estimates (bad debts, provisions) are also period-end adjustments.', 'Reversing entries simplify recording when the real transaction arrives.'] },
    ],
    quiz: [
      { q: 'Under accrual accounting, revenue is recognised when…', o: ['Cash is received', 'It is earned (goods/services delivered)', 'The invoice is paid', 'The year ends'], a: 1, e: 'Revenue follows performance, not cash.' },
      { q: 'Insurance paid in advance is initially recorded as…', o: ['An expense', 'A liability', 'An asset (prepaid)', 'Revenue'], a: 2, e: 'It’s a future benefit — prepaid expense is an asset.' },
      { q: 'Customer deposits received before delivery are…', o: ['Revenue', 'An asset', 'A liability (unearned revenue)', 'Equity'], a: 2, e: 'You owe the service or a refund.' },
      { q: 'Wages earned by staff but unpaid at year-end require…', o: ['Dr Wages Payable / Cr Wages Expense', 'Dr Wages Expense / Cr Wages Payable', 'Dr Wages Expense / Cr Bank', 'No entry'], a: 1, e: 'Accrued expense: record the expense and the liability.' },
      { q: 'Which account is usually NOT touched by an adjusting entry?', o: ['Prepaid rent', 'Unearned revenue', 'Cash', 'Depreciation expense'], a: 2, e: 'Adjustments fix timing; cash was already recorded (or hasn’t moved yet).' },
      { q: '$12,000 annual subscription received 1 Oct. Revenue to recognise by 31 Dec?', o: ['$12,000', '$3,000', '$9,000', '$1,000'], a: 1, e: '3 of 12 months: $3,000. $9,000 remains unearned.' },
      { q: 'Reversing entries are typically made for…', o: ['Depreciation', 'Accruals', 'Closing entries', 'Error corrections'], a: 1, e: 'Reversing accruals simplifies recording the actual later transaction.' },
    ],
    cards: [
      ['Accrual basis', 'Recognise revenue when earned and expenses when incurred, regardless of cash.'],
      ['Prepaid expense', 'Payment in advance for future benefit — an asset until used.'],
      ['Unearned (deferred) revenue', 'Cash received before delivering goods/services — a liability.'],
      ['Accrued expense', 'Expense incurred but not yet paid/billed — record a liability.'],
      ['Accrued revenue', 'Revenue earned but not yet billed/received — record an asset.'],
      ['Reversing entry', 'Entry on the first day of a period that reverses a prior accrual.'],
    ],
  });

  /* =============================== CH 9 =============================== */
  HF.addChapter({
    id: 'income-statement',
    part: 'p2',
    title: 'The Income Statement',
    subtitle: 'Profit & Loss: the movie of the business’s performance',
    art: 'chart',
    level: 'Intermediate',
    minutes: 25,
    quote: 'Revenue is vanity, profit is sanity, cash is king.',
    goals: ['Build single-step and multi-step income statements', 'Calculate gross profit, operating profit, EBITDA and net profit', 'Understand COGS, other income, finance costs, tax, EPS and OCI'],
    blocks: [
      { t: 'h', text: 'A movie, not a photo' },
      { t: 'p', html: 'The <b>income statement</b> (a.k.a. <b>Profit & Loss</b>, P&L, statement of profit or loss) shows performance <b>over a period</b> — a month, a quarter, a year. Contrast this with the balance sheet, a photo at one <b>point in time</b>.' },
      { t: 'formula', html: 'Revenue − Expenses = Net Profit (or Loss)' },

      { t: 'h', text: 'The multi-step layout' },
      { t: 'p', html: 'A multi-step statement shows profit in layers, so you can see <i>where</i> money is made or lost.' },
      {
        t: 'table',
        caption: 'Max’s Bikes — Income Statement for the year ended 31 Dec 2026',
        head: ['', '$', '$'],
        rows: [
          ['Revenue (sales of bikes & services)', '', '<b>250,000</b>'],
          ['Less: Sales returns & discounts', '', '(5,000)'],
          ['<b>Net revenue</b>', '', '<b>245,000</b>'],
          ['Cost of goods sold', '', '(147,000)'],
          { _cls: 'tot', cells: ['<b>Gross profit</b>', '', '<b>98,000</b>'] },
          ['Selling expenses (ads, sales wages)', '(22,000)', ''],
          ['Administrative expenses (rent, office, accounting)', '(30,000)', ''],
          ['Depreciation', '(6,000)', '(58,000)'],
          { _cls: 'tot', cells: ['<b>Operating profit (EBIT)</b>', '', '<b>40,000</b>'] },
          ['Other income (gain on sale of old van)', '', '1,500'],
          ['Finance costs (interest)', '', '(3,500)'],
          { _cls: 'tot', cells: ['<b>Profit before tax</b>', '', '<b>38,000</b>'] },
          ['Income tax expense (25%)', '', '(9,500)'],
          { _cls: 'tot', cells: ['<b>Net profit for the year</b>', '', '<b>28,500</b>'] },
        ],
      },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '🏷️', t: 'Gross profit', d: 'Net revenue − COGS. How much the product itself earns. <b>Gross margin</b> = GP ÷ revenue (here 40%).', color: 'green' },
          { icon: '⚙️', t: 'Operating profit (EBIT)', d: 'Gross profit − operating expenses. Profit from the core business before financing and tax.', color: 'blue' },
          { icon: '🧮', t: 'EBITDA', d: 'EBIT + depreciation & amortisation = 46,000. A rough proxy for operating cash generation. Not a GAAP/IFRS measure!', color: 'yellow' },
          { icon: '🏦', t: 'Finance costs', d: 'Interest on loans/leases. Below operating profit because it depends on how you’re funded, not how you operate.', color: 'red' },
          { icon: '🏛️', t: 'Income tax', d: 'Tax on profits (current + deferred — see Chapter 19).', color: 'purple' },
          { icon: '🎯', t: 'Net profit', d: 'The “bottom line”. Belongs to the owners; flows into retained earnings.', color: 'green' },
        ],
      },
      { t: 'h3', text: 'Cost of goods sold, the formula' },
      { t: 'formula', html: 'COGS = Opening inventory + Purchases − Closing inventory', note: 'For a retailer or manufacturer. Service businesses may have “cost of services” or none at all.' },
      { t: 'pencil', items: [{ q: 'Opening inventory $20,000, purchases $150,000, closing inventory $23,000. COGS?', input: true, a: '20,000 + 150,000 − 23,000 = <b>$147,000</b> — matches the statement above.' }, { q: 'If closing inventory were <b>overstated</b> by $5,000, what happens to profit?', a: 'COGS is understated by $5,000 → gross profit and net profit are <b>overstated</b> by $5,000 (before tax). Inventory errors flow straight to profit!' }] },

      { t: 'h', text: 'Single-step, by nature or by function' },
      {
        t: 'compare',
        cols: [
          { t: 'Single-step', color: 'yellow', items: ['All revenues together, all expenses together', 'One subtraction', 'Simple, common for small businesses'] },
          { t: 'By function (cost of sales method)', color: 'blue', items: ['Groups expenses by what they’re for: cost of sales, distribution, admin', 'Shows gross profit', 'Requires notes on depreciation & staff costs'] },
          { t: 'By nature', color: 'green', items: ['Groups expenses by what they are: raw materials, staff costs, depreciation', 'No gross profit line', 'Common in continental Europe'] },
        ],
      },
      { t: 'p', html: 'IFRS lets companies choose (IFRS 18, effective 2027, adds required subtotals like <b>operating profit</b> and new categories — operating, investing, financing). US GAAP uses multi-step formats in practice.' },

      { t: 'h', text: 'Below the line: EPS & OCI' },
      { t: 'list', items: ['<b>Earnings per share (EPS)</b> = (net profit − preferred dividends) ÷ weighted average ordinary shares. Required for listed companies.', '<b>Other comprehensive income (OCI)</b>: certain gains/losses that bypass profit, e.g., revaluation surplus on property, some foreign currency translation differences, actuarial gains on pensions. <b>Total comprehensive income</b> = profit + OCI.', '<b>Discontinued operations</b>: results of a business segment being sold/closed are shown separately so investors can see the ongoing business.'] },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch9-where',
          title: 'Where does it go on the P&L?',
          bins: [
            { id: 'C', label: 'Cost of sales', color: '#e4572e' },
            { id: 'O', label: 'Operating expense', color: '#2e86ab' },
            { id: 'F', label: 'Finance cost', color: '#8e5ea2' },
            { id: 'X', label: 'Not on the P&L', color: '#55606e' },
          ],
          items: [
            { text: 'Cost of bikes sold', bin: 'C' },
            { text: 'Freight-in on bikes purchased', bin: 'C', why: 'Costs to get inventory ready for sale are part of inventory cost → COGS.' },
            { text: 'Shop rent', bin: 'O' },
            { text: 'Advertising', bin: 'O' },
            { text: 'Interest on bank loan', bin: 'F' },
            { text: 'Repayment of loan principal', bin: 'X', why: 'Principal reduces a liability — not an expense.' },
            { text: 'Owner drawings / dividends', bin: 'X', why: 'Distributions to owners go through equity.' },
            { text: 'Depreciation of the shop fit-out', bin: 'O' },
            { text: 'Purchase of a new van', bin: 'X', why: 'Capital expenditure — an asset on the balance sheet.' },
            { text: 'Lease interest (IFRS 16)', bin: 'F' },
          ],
        },
      },
      { t: 'odoo', path: 'Accounting > Reporting > Profit and Loss', html: 'Odoo’s P&L groups accounts by <b>account type</b>: <i>Income</i> and <i>Other Income</i> at the top, <i>Cost of Revenue</i> for gross profit, then <i>Expenses</i> and <i>Depreciation</i>. Use the filters for date ranges, comparisons (vs previous period/year), <b>analytic</b> filters (per department or project), and unfold any line down to the journal items. Localizations may provide country-specific P&L layouts.' },
      { t: 'bullets', items: ['The income statement covers a period; the balance sheet is a point in time.', 'Multi-step: net revenue → gross profit → operating profit → profit before tax → net profit.', 'COGS = opening inventory + purchases − closing inventory.', 'EBITDA = EBIT + D&A (a non-standard but popular measure).', 'Capital spending, loan principal and drawings are NOT expenses.', 'OCI holds certain gains/losses outside profit; total comprehensive income = profit + OCI.'] },
    ],
    quiz: [
      { q: 'Gross profit equals…', o: ['Revenue − all expenses', 'Net revenue − cost of goods sold', 'Operating profit − interest', 'Revenue − tax'], a: 1, e: 'Gross profit = net revenue − COGS.' },
      { q: 'Opening inventory 10k, purchases 60k, closing inventory 15k. COGS is…', o: ['55k', '65k', '85k', '45k'], a: 0, e: '10 + 60 − 15 = 55.' },
      { q: 'Interest on a loan is classified as…', o: ['Cost of sales', 'Operating expense', 'Finance cost', 'Not an expense'], a: 2, e: 'Finance costs sit below operating profit.' },
      { q: 'Which is NOT an expense?', o: ['Depreciation', 'Wages', 'Repaying loan principal', 'Advertising'], a: 2, e: 'Principal repayment reduces a liability.' },
      { q: 'EBITDA is…', o: ['A required IFRS line item', 'Profit before interest, tax, depreciation and amortisation', 'Cash in the bank', 'Gross profit minus tax'], a: 1, e: 'A popular non-GAAP measure.' },
      { q: 'If closing inventory is overstated, net profit is…', o: ['Overstated', 'Understated', 'Unaffected', 'Zero'], a: 0, e: 'Higher closing inventory → lower COGS → higher profit.' },
      { q: 'A revaluation gain on land under IFRS usually goes to…', o: ['Revenue', 'Other comprehensive income', 'Cost of sales', 'Cash flow statement only'], a: 1, e: 'Revaluation surplus is recognised in OCI and accumulated in equity.' },
    ],
    cards: [
      ['Income statement', 'Report of revenues, expenses and profit over a period (P&L).'],
      ['Gross profit', 'Net revenue − cost of goods sold.'],
      ['Operating profit (EBIT)', 'Gross profit − operating expenses.'],
      ['EBITDA', 'Earnings before interest, tax, depreciation and amortisation.'],
      ['COGS formula', 'Opening inventory + purchases − closing inventory.'],
      ['OCI', 'Other comprehensive income: gains/losses recognised outside profit (e.g., revaluation surplus).'],
      ['EPS', 'Earnings per share = profit attributable to ordinary shareholders ÷ weighted average shares.'],
    ],
  });

  /* =============================== CH 10 =============================== */
  HF.addChapter({
    id: 'balance-sheet',
    part: 'p2',
    title: 'The Balance Sheet',
    subtitle: 'A snapshot of what you own, what you owe, and what’s yours',
    art: 'statements',
    level: 'Intermediate',
    minutes: 25,
    quote: 'The income statement tells you how fast you’re driving. The balance sheet tells you how much fuel is left in the tank.',
    goals: ['Prepare a classified balance sheet', 'Distinguish current and non-current items', 'Compute working capital', 'Link the P&L, statement of changes in equity and the balance sheet'],
    blocks: [
      { t: 'h', text: 'A photo at one moment' },
      { t: 'p', html: 'The <b>balance sheet</b> (statement of financial position) lists assets, liabilities and equity <b>at a date</b> — “as at 31 December 2026”. It is the accounting equation, dressed up for a party.' },
      {
        t: 'table',
        caption: 'Max’s Bikes — Balance Sheet as at 31 December 2026',
        head: ['', '$', '$'],
        rows: [
          ['<b>ASSETS</b>', '', ''],
          ['<i>Non-current assets</i>', '', ''],
          ['Vehicles & equipment, at cost', '45,000', ''],
          ['Less: accumulated depreciation', '(12,000)', '33,000'],
          ['<i>Current assets</i>', '', ''],
          ['Inventory', '23,000', ''],
          ['Accounts receivable (net of allowance)', '14,500', ''],
          ['Prepaid expenses', '1,500', ''],
          ['Cash and bank', '18,000', '57,000'],
          { _cls: 'tot', cells: ['<b>Total assets</b>', '', '<b>90,000</b>'] },
          ['<b>EQUITY AND LIABILITIES</b>', '', ''],
          ['<i>Equity</i>', '', ''],
          ['Owner’s capital', '30,000', ''],
          ['Retained earnings', '22,500', '52,500'],
          ['<i>Non-current liabilities</i>', '', ''],
          ['Bank loan (due after 12 months)', '', '16,000'],
          ['<i>Current liabilities</i>', '', ''],
          ['Accounts payable', '12,000', ''],
          ['Accrued expenses', '2,000', ''],
          ['Tax payable', '3,500', ''],
          ['Current portion of bank loan', '4,000', '21,500'],
          { _cls: 'tot', cells: ['<b>Total equity and liabilities</b>', '', '<b>90,000</b>'] },
        ],
      },
      { t: 'say', who: 'max', html: 'Total assets $90,000 = equity + liabilities $90,000. It… balances! Is that why it’s called a <i>balance</i> sheet?' },
      { t: 'say', who: 'penny', right: true, html: 'Yes! If it didn’t balance, something would be broken. Notice how the loan was split: the $4,000 due within 12 months is <b>current</b>; the rest is non-current.' },

      { t: 'h', text: 'Current vs non-current' },
      {
        t: 'compare',
        cols: [
          { t: 'Current', color: 'yellow', items: ['Expected to be realised/settled within <b>12 months</b> or the normal operating cycle', 'Assets: cash, receivables, inventory, prepaid', 'Liabilities: payables, accruals, tax due, short-term debt, current portion of long-term debt'] },
          { t: 'Non-current', color: 'blue', items: ['Beyond 12 months', 'Assets: property, plant & equipment, intangibles, long-term investments, deferred tax assets', 'Liabilities: long-term loans, bonds, lease liabilities, deferred tax liabilities, long-term provisions'] },
        ],
      },
      { t: 'formula', html: 'Working capital = Current assets − Current liabilities', note: 'Max: 57,000 − 21,500 = 35,500. Positive = a cushion to pay short-term bills.' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch10-cur',
          title: 'Classify the balance sheet',
          bins: [
            { id: 'CA', label: 'Current asset', color: '#2e86ab' },
            { id: 'NCA', label: 'Non-current asset', color: '#00798c' },
            { id: 'CL', label: 'Current liability', color: '#e4572e' },
            { id: 'NCL', label: 'Non-current liability', color: '#a63d1f' },
            { id: 'EQ', label: 'Equity', color: '#3a9d5d' },
          ],
          items: [
            { text: 'Inventory', bin: 'CA' },
            { text: 'Delivery van', bin: 'NCA' },
            { text: 'Software licence (5 yrs)', bin: 'NCA', why: 'An intangible non-current asset.' },
            { text: 'Customer receivables', bin: 'CA' },
            { text: 'Supplier payables', bin: 'CL' },
            { text: 'VAT/GST payable', bin: 'CL' },
            { text: '10-year mortgage (portion due after 1 year)', bin: 'NCL' },
            { text: 'Loan instalments due in next 12 months', bin: 'CL' },
            { text: 'Retained earnings', bin: 'EQ' },
            { text: 'Share capital', bin: 'EQ' },
            { text: 'Customer deposits for next month', bin: 'CL', why: 'Unearned revenue settled within 12 months.' },
            { text: 'Prepaid insurance (9 months left)', bin: 'CA' },
          ],
        },
      },
      { t: 'watch', html: 'Order varies! US GAAP balance sheets usually list items in <b>order of liquidity</b> (cash first). Many IFRS reporters list <b>non-current assets first</b> and equity before liabilities. Same content — different order. Don’t panic when a statement looks “upside down”.' },

      { t: 'h', text: 'How the statements connect' },
      { t: 'flow', items: [{ t: 'Income statement<br><b>Net profit 28,500</b>', c: '#b5e3c4' }, { t: 'Statement of changes in equity<br><b>Opening RE 4,000 + 28,500 − drawings 10,000</b>', c: '#fff3a8' }, { t: 'Balance sheet<br><b>Retained earnings 22,500</b>', c: '#bfe0f2' }] },
      { t: 'p', html: 'The <b>statement of changes in equity</b> (SOCE) bridges them: opening equity + profit (+ OCI) + new capital − drawings/dividends = closing equity. And the cash flow statement (next chapter) explains the change in the cash line.' },
      {
        t: 'table',
        caption: 'Statement of changes in equity — 2026',
        head: ['', 'Capital', 'Retained earnings', 'Total'],
        rows: [
          ['Opening balance 1 Jan', '25,000', '4,000', '29,000'],
          ['Capital introduced', '5,000', '', '5,000'],
          ['Profit for the year', '', '28,500', '28,500'],
          ['Drawings', '', '(10,000)', '(10,000)'],
          { _cls: 'tot', cells: ['Closing balance 31 Dec', '30,000', '22,500', '52,500'] },
        ],
      },
      { t: 'brain', html: 'Max made $28,500 profit, but cash is only $18,000. Where could the “missing” profit be hiding on the balance sheet? <i>(Look at receivables, inventory, the van, and the loan repayments.)</i>' },
      { t: 'odoo', path: 'Accounting > Reporting > Balance Sheet', html: 'In Odoo, the balance sheet shows <b>Current Year Earnings</b> (this year’s unallocated profit, computed live from P&L accounts) and <b>Retained Earnings / Previous years unallocated earnings</b> inside equity — no closing entry required. Use “Comparison” to show several dates side by side.' },
      { t: 'bullets', items: ['Balance sheet = financial position at a date: A = L + E.', 'Classify current (≤12 months) vs non-current.', 'Working capital = current assets − current liabilities.', 'Long-term debt is split into current portion and non-current portion.', 'Profit → retained earnings via the statement of changes in equity.'] },
    ],
    quiz: [
      { q: 'The balance sheet reports…', o: ['Performance over a period', 'Financial position at a point in time', 'Cash flows only', 'Tax due'], a: 1, e: 'It’s a snapshot “as at” a date.' },
      { q: 'Which is a current liability?', o: ['Loan due in 5 years', 'Accounts payable', 'Share capital', 'Equipment'], a: 1, e: 'Payables are normally settled within 12 months.' },
      { q: 'Current assets 80k, current liabilities 50k. Working capital?', o: ['130k', '30k', '1.6', '−30k'], a: 1, e: '80 − 50 = 30k.' },
      { q: 'Net profit flows into which balance sheet line?', o: ['Cash', 'Retained earnings', 'Share capital', 'Accounts receivable'], a: 1, e: 'Via the statement of changes in equity.' },
      { q: 'A $50k loan with $10k due next year appears as…', o: ['$50k non-current', '$50k current', '$10k current + $40k non-current', '$40k current + $10k non-current'], a: 2, e: 'Split the current portion out.' },
      { q: 'Opening equity 40k, profit 15k, dividends 5k, new shares 10k. Closing equity?', o: ['60k', '50k', '70k', '55k'], a: 0, e: '40 + 15 − 5 + 10 = 60.' },
    ],
    cards: [
      ['Balance sheet', 'Statement of financial position: assets, liabilities and equity at a date.'],
      ['Current asset', 'Expected to be realised within 12 months or the operating cycle.'],
      ['Current liability', 'Due to be settled within 12 months or the operating cycle.'],
      ['Working capital', 'Current assets − current liabilities.'],
      ['Statement of changes in equity', 'Reconciles opening to closing equity: profit, OCI, capital, dividends/drawings.'],
      ['Retained earnings', 'Accumulated profits kept in the business (not distributed).'],
    ],
  });

  /* =============================== CH 11 =============================== */
  HF.addChapter({
    id: 'cash-flow',
    part: 'p2',
    title: 'The Cash Flow Statement',
    subtitle: 'Following the money: operating, investing, financing',
    art: 'coins',
    level: 'Intermediate',
    minutes: 30,
    quote: 'Profitable companies go bankrupt all the time. They just run out of cash first.',
    goals: ['Classify cash flows as operating, investing or financing', 'Prepare operating cash flow using the indirect method', 'Explain the direct method and free cash flow'],
    blocks: [
      { t: 'h', text: 'Why profit isn’t enough' },
      { t: 'story', panels: [{ who: 'max', text: 'We made $28,500 profit! Time to celebrate!' }, { who: 'penny', text: 'Lovely. But the supplier wants $12,000 on Friday and the bank has $18,000…' }, { art: 'boxes', text: 'Half your “profit” is sitting on shelves as bikes, and a chunk is owed by customers.' }, { who: 'max', think: true, text: 'So profit and cash are… different animals.' }] },
      { t: 'p', html: 'The <b>statement of cash flows</b> explains how cash changed during the period, in three buckets:' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '🔄', t: 'Operating (CFO)', d: 'Cash from the main business: receipts from customers, payments to suppliers and staff, (usually) interest and taxes.', color: 'green' },
          { icon: '🏗️', t: 'Investing (CFI)', d: 'Buying and selling long-term assets and investments: equipment, property, shares in other companies, loans made.', color: 'blue' },
          { icon: '🏦', t: 'Financing (CFF)', d: 'Dealing with funders: borrowing and repaying loans, issuing shares, paying dividends, lease principal.', color: 'purple' },
        ],
      },
      { t: 'formula', html: 'CFO + CFI + CFF = Change in cash', note: 'Opening cash + change = closing cash (which must match the balance sheet!)' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch11-cf',
          title: 'Operating, investing or financing?',
          bins: [
            { id: 'O', label: 'Operating', color: '#3a9d5d' },
            { id: 'I', label: 'Investing', color: '#2e86ab' },
            { id: 'F', label: 'Financing', color: '#8e5ea2' },
          ],
          items: [
            { text: 'Cash received from customers', bin: 'O' },
            { text: 'Wages paid', bin: 'O' },
            { text: 'Bought a delivery van', bin: 'I' },
            { text: 'Sold old equipment', bin: 'I' },
            { text: 'Took out a bank loan', bin: 'F' },
            { text: 'Repaid loan principal', bin: 'F' },
            { text: 'Paid dividends', bin: 'F', why: 'Under US GAAP always financing; IFRS allows operating or financing.' },
            { text: 'Owner invested more capital', bin: 'F' },
            { text: 'Paid suppliers for inventory', bin: 'O' },
            { text: 'Income tax paid', bin: 'O', why: 'Normally operating unless specifically tied to investing/financing.' },
            { text: 'Bought shares in another company (investment)', bin: 'I' },
          ],
        },
      },
      { t: 'watch', html: 'Interest and dividends are classification hot spots. <b>US GAAP</b>: interest paid & received and dividends received → operating; dividends paid → financing. <b>IFRS (IAS 7)</b> currently allows a choice, applied consistently. IFRS 18 (from 2027) tightens this for most companies: interest & dividends received → investing, interest & dividends paid → financing.' },

      { t: 'h', text: 'The indirect method (most common)' },
      { t: 'p', html: 'Start with net profit and <b>undo</b> everything that isn’t cash:' },
      {
        t: 'steps',
        items: [
          { t: 'Start with profit before tax (or net profit)', d: 'Max: net profit 28,500.' },
          { t: 'Add back non-cash expenses', d: 'Depreciation and amortisation, impairment, provisions. They reduced profit but no cash left.' },
          { t: 'Remove non-operating gains/losses', d: 'Subtract a gain on sale of assets (the cash goes in investing); add back a loss.' },
          { t: 'Adjust for working capital changes', d: 'Increase in current assets (receivables, inventory, prepaid) → <b>subtract</b>. Increase in current liabilities (payables, accruals) → <b>add</b>. And vice versa.' },
        ],
      },
      { t: 'sticky', side: 'right', html: 'Working capital trick:<br>Asset ↑ = cash ↓ <br>Liability ↑ = cash ↑<br>(You tied up cash in stock, or a supplier is financing you.)' },
      {
        t: 'table',
        caption: 'Max’s Bikes — Cash flow statement 2026 (indirect)',
        head: ['', '$'],
        rows: [
          ['<b>Operating activities</b>', ''],
          ['Net profit', '28,500'],
          ['Add: depreciation', '6,000'],
          ['Less: gain on sale of van', '(1,500)'],
          ['Increase in inventory', '(3,000)'],
          ['Increase in receivables', '(6,500)'],
          ['Increase in prepaid expenses', '(500)'],
          ['Increase in payables', '4,000'],
          ['Increase in accrued expenses & tax payable', '2,000'],
          { _cls: 'tot', cells: ['<b>Net cash from operating activities</b>', '<b>29,000</b>'] },
          ['<b>Investing activities</b>', ''],
          ['Purchase of equipment', '(20,000)'],
          ['Proceeds from sale of old van', '4,500'],
          { _cls: 'tot', cells: ['<b>Net cash used in investing</b>', '<b>(15,500)</b>'] },
          ['<b>Financing activities</b>', ''],
          ['Capital introduced', '5,000'],
          ['Loan repayments', '(4,000)'],
          ['Drawings', '(10,000)'],
          { _cls: 'tot', cells: ['<b>Net cash used in financing</b>', '<b>(9,000)</b>'] },
          { _cls: 'tot', cells: ['<b>Net increase in cash</b>', '<b>4,500</b>'] },
          ['Cash at 1 January', '13,500'],
          { _cls: 'tot', cells: ['<b>Cash at 31 December</b>', '<b>18,000</b> ✔ matches the balance sheet'] },
        ],
      },
      {
        t: 'pencil',
        html: 'Net profit is $50,000. Depreciation $8,000. Receivables rose $5,000; inventory fell $3,000; payables fell $2,000. Compute operating cash flow.',
        items: [{ q: 'Operating cash flow = ?', input: true, a: '50,000 + 8,000 − 5,000 + 3,000 − 2,000 = <b>$54,000</b>.' }],
      },

      { t: 'h', text: 'The direct method' },
      { t: 'p', html: 'Shows actual operating receipts and payments: cash from customers, cash to suppliers, cash to employees, interest, taxes. It’s more intuitive and encouraged by IFRS/GAAP, but less common because it’s harder to extract from traditional ledgers. Both methods give the <b>same total CFO</b>.' },
      { t: 'formula', html: 'Cash from customers = Revenue − ΔReceivables', note: 'If receivables went up, you collected less than you sold.' },

      { t: 'h', text: 'Free cash flow' },
      { t: 'formula', html: 'Free cash flow = CFO − Capital expenditure', note: 'Max: 29,000 − 20,000 = 9,000 available for debt repayment, drawings or growth.' },
      {
        t: 'chat',
        title: 'Profit vs Cash: who matters more?',
        left: 'Profit',
        right: 'Cash',
        lines: [
          ['L', 'I measure whether the business model actually works. Without me, you don’t know if you’re creating value.'],
          ['R', 'Cute. But nobody pays salaries with “value”. They pay with me.'],
          ['L', 'You’re lumpy. One big equipment purchase and you look terrible, even if the year was great.'],
          ['R', 'And you can be massaged with estimates. I’m much harder to fake.'],
          ['L', 'Fine. Investors should look at both of us… together.'],
          ['R', 'Finally, something we agree on.'],
        ],
      },
      { t: 'odoo', path: 'Accounting > Reporting > Cash Flow Statement', html: 'Odoo (Enterprise) generates a cash flow statement using the indirect method. It relies on <b>account tags</b> on your accounts (e.g., “Operating activities”, “Investing & extraordinary activities”, “Financing activities”) to classify movements — so tag new accounts correctly when you create them.' },
      { t: 'bullets', items: ['Cash flow statement explains the change in cash via operating, investing and financing activities.', 'Indirect method: profit + non-cash items ± working capital changes.', 'Asset increase → cash decrease; liability increase → cash increase.', 'Direct and indirect methods give the same operating total.', 'Free cash flow = CFO − capex.'] },
    ],
    quiz: [
      { q: 'Buying equipment for cash is a…', o: ['Operating outflow', 'Investing outflow', 'Financing outflow', 'Non-cash item'], a: 1, e: 'Long-term asset purchases are investing activities.' },
      { q: 'Under the indirect method, depreciation is…', o: ['Subtracted', 'Added back', 'Ignored', 'Shown in financing'], a: 1, e: 'It reduced profit but used no cash.' },
      { q: 'An increase in accounts receivable…', o: ['Increases operating cash flow', 'Decreases operating cash flow', 'Has no effect', 'Is a financing item'], a: 1, e: 'You booked revenue but didn’t collect the cash.' },
      { q: 'Repaying a bank loan’s principal is…', o: ['Operating', 'Investing', 'Financing', 'Not a cash flow'], a: 2, e: 'Dealings with lenders/owners are financing.' },
      { q: 'Net profit 20k, depreciation 5k, inventory ↑ 4k, payables ↑ 3k. CFO =', o: ['24k', '22k', '32k', '18k'], a: 0, e: '20 + 5 − 4 + 3 = 24.' },
      { q: 'A gain on sale of equipment in the indirect method is…', o: ['Added', 'Subtracted from profit', 'Shown in financing', 'Ignored'], a: 1, e: 'Remove it from operating; the full sale proceeds appear in investing.' },
      { q: 'Free cash flow equals…', o: ['Net profit − dividends', 'CFO − capital expenditure', 'Cash + receivables', 'CFI + CFF'], a: 1, e: 'Cash generated after maintaining/expanding the asset base.' },
    ],
    cards: [
      ['Operating activities', 'Cash flows from the main revenue-producing activities.'],
      ['Investing activities', 'Cash flows from buying/selling long-term assets and investments.'],
      ['Financing activities', 'Cash flows with lenders and owners: loans, shares, dividends.'],
      ['Indirect method', 'Starts with profit and adjusts for non-cash items and working capital changes.'],
      ['Direct method', 'Lists actual operating cash receipts and payments.'],
      ['Free cash flow', 'Operating cash flow − capital expenditure.'],
    ],
  });

  /* =============================== CH 12 =============================== */
  HF.addChapter({
    id: 'closing-books',
    part: 'p2',
    title: 'Closing the Books',
    subtitle: 'Resetting the scoreboard and locking the vault',
    art: 'lock',
    level: 'Intermediate',
    minutes: 20,
    quote: 'Closing isn’t the end of the year. It’s the start of a clean one.',
    goals: ['Prepare closing entries using an income summary', 'Close drawings/dividends to equity', 'Prepare a post-closing trial balance', 'Run a practical month-end close checklist'],
    blocks: [
      { t: 'h', text: 'The four closing entries' },
      { t: 'p', html: 'At year-end (in manual or traditional systems), temporary accounts are zeroed out and their net result transferred to equity. The classic method uses a temporary <b>Income Summary</b> account:' },
      { t: 'steps', items: [{ t: 'Close revenues', d: 'Debit each revenue account, credit Income Summary.' }, { t: 'Close expenses', d: 'Credit each expense account, debit Income Summary.' }, { t: 'Close Income Summary', d: 'Its balance = net profit (credit) or loss (debit). Transfer to Retained Earnings (or owner’s Capital).' }, { t: 'Close drawings / dividends', d: 'Credit Drawings/Dividends, debit Capital/Retained Earnings.' }] },
      { t: 'entry', title: '1. Close revenue', lines: [['Sales Revenue', 245000, 0], ['Other Income', 1500, 0], ['Income Summary', 0, 246500]] },
      { t: 'entry', title: '2. Close expenses', lines: [['Income Summary', 218000, 0], ['Cost of Goods Sold', 0, 147000], ['Operating Expenses', 0, 58000], ['Interest Expense', 0, 3500], ['Income Tax Expense', 0, 9500]] },
      { t: 'entry', title: '3. Close income summary (profit 28,500)', lines: [['Income Summary', 28500, 0], ['Retained Earnings', 0, 28500]] },
      { t: 'entry', title: '4. Close drawings', lines: [['Retained Earnings', 10000, 0], ['Drawings', 0, 10000]] },
      { t: 'p', html: 'After closing, revenue, expenses, drawings and income summary all show <b>zero</b>. A <b>post-closing trial balance</b> lists only permanent (balance sheet) accounts.' },
      { t: 'watch', html: 'Drawings/dividends are closed <b>directly to equity</b>, not through Income Summary — they aren’t part of profit.' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch12-close',
          title: 'Closed or carried forward?',
          bins: [
            { id: 'T', label: 'Closed at year-end', color: '#e4572e' },
            { id: 'P', label: 'Carried forward', color: '#2e86ab' },
          ],
          items: [
            { text: 'Sales revenue', bin: 'T' },
            { text: 'Rent expense', bin: 'T' },
            { text: 'Dividends declared', bin: 'T' },
            { text: 'Accounts payable', bin: 'P' },
            { text: 'Retained earnings', bin: 'P' },
            { text: 'Accumulated depreciation', bin: 'P', why: 'A contra-asset — a balance sheet account.' },
            { text: 'Depreciation expense', bin: 'T' },
            { text: 'Unearned revenue', bin: 'P', why: 'A liability.' },
            { text: 'Interest income', bin: 'T' },
            { text: 'Inventory', bin: 'P' },
          ],
        },
      },

      { t: 'h', text: 'A real-world month-end checklist' },
      {
        t: 'table',
        head: ['When', 'Task', 'Why'],
        rows: [
          ['Day −2 to 0', 'Remind teams to submit invoices, expenses, timesheets; confirm deliveries shipped/received', 'Cut-off'],
          ['Day 1', 'Import & reconcile all bank, card and cash accounts', 'Cash is the anchor of truth'],
          ['Day 1–2', 'Post vendor bills received; accrue goods/services received but not billed', 'Complete liabilities'],
          ['Day 1–2', 'Invoice all delivered goods/services; accrue unbilled revenue; defer prepaid revenue', 'Revenue cut-off'],
          ['Day 2', 'Depreciation, amortisation, prepaid & deferral entries', 'Allocation'],
          ['Day 2', 'Inventory valuation & count adjustments', 'COGS accuracy'],
          ['Day 2–3', 'Payroll accruals, bonus & leave provisions', 'Complete expenses'],
          ['Day 3', 'FX revaluation of foreign-currency balances; intercompany reconciliation', 'Multi-currency / groups'],
          ['Day 3', 'Reconcile AR & AP ledgers to control accounts; review aged lists', 'Sub-ledger integrity'],
          ['Day 3–4', 'Tax return (VAT/GST) and tax closing entry', 'Compliance'],
          ['Day 4', 'Analytical review vs budget/prior month; investigate variances', 'Catch errors'],
          ['Day 5', 'Management pack; set lock date for the period', 'Report & protect'],
        ],
      },
      { t: 'say', who: 'audrey', html: 'Every balance sheet account should have a <b>reconciliation</b> — a schedule explaining what makes up the balance. If you can’t explain a number, I will find it. 🔍' },
      { t: 'odoo', title: 'Closing in Odoo', path: 'Accounting > Accounting > Lock Dates', html: '<ul><li>No closing entries are required: Odoo calculates <b>Current Year Earnings</b> on the fly and, in a new fiscal year, shows the past result as <b>undistributed / unallocated earnings</b>. Many companies still post a year-end Misc entry to move it into a formal <b>Retained Earnings</b> account if local rules require it.</li><li>Use <b>lock dates</b> to block changes to closed periods (separate dates exist for tax, sales/purchase journals and everything — names vary by version).</li><li>Some editions offer a guided <b>closing checklist / activities</b> on the Accounting dashboard to track tasks.</li></ul>' },
      { t: 'bullets', items: ['Closing entries zero revenue, expense and drawings accounts.', 'Income Summary collects the net result, then moves it to retained earnings/capital.', 'Drawings/dividends close directly to equity.', 'Post-closing TB: only balance sheet accounts remain.', 'Modern close = cut-off, reconcile, adjust, review, report, lock.'] },
    ],
    quiz: [
      { q: 'Income Summary after closing revenues and expenses shows a credit balance of $12,000. This means…', o: ['A loss of 12k', 'A profit of 12k', 'Cash of 12k', 'An error'], a: 1, e: 'Credits (revenues) exceeded debits (expenses).' },
      { q: 'Dividends are closed to…', o: ['Income Summary', 'Retained Earnings', 'Cash', 'Revenue'], a: 1, e: 'They’re distributions, not expenses.' },
      { q: 'Which account appears on a post-closing trial balance?', o: ['Rent expense', 'Sales', 'Accounts receivable', 'Income summary'], a: 2, e: 'Only permanent accounts remain.' },
      { q: 'To close an expense account, you…', o: ['Debit it', 'Credit it', 'Leave it', 'Reverse it next year'], a: 1, e: 'Expenses have debit balances; credit them to zero.' },
      { q: 'In Odoo, how is the year’s profit carried into equity?', o: ['Automatically shown as current year/undistributed earnings', 'Only by manual closing entries for every account', 'Through bank reconciliation', 'It isn’t'], a: 0, e: 'Odoo computes it; a Misc entry to retained earnings is optional per local rules.' },
      { q: 'The main purpose of a lock date is to…', o: ['Speed up reports', 'Prevent changes to closed periods', 'Close the bank account', 'Calculate tax'], a: 1, e: 'It protects finalised numbers.' },
    ],
    cards: [
      ['Closing entries', 'Entries that zero temporary accounts and transfer the result to equity.'],
      ['Income summary', 'Temporary account used to collect revenues and expenses during closing.'],
      ['Post-closing trial balance', 'TB after closing; only permanent accounts.'],
      ['Month-end close', 'Cut-off, reconcile, adjust, review, report and lock a period.'],
      ['Balance sheet reconciliation', 'A schedule proving and explaining each balance sheet account’s balance.'],
    ],
  });
})();
