/* PART 4 — Advanced Accounting */
(function () {
  const HF = window.HF;
  HF.addPart({ id: 'p4', n: 4, title: 'Advanced Accounting', color: '#8e5ea2', badge: 'part4', desc: 'Tax, financial analysis, cost & management accounting, budgeting, IFRS 15 & 16, groups, foreign currency, standards, audit & ethics.' });

  /* =============================== CH 19 =============================== */
  HF.addChapter({
    id: 'taxes',
    part: 'p4',
    title: 'Taxes: VAT/GST, Sales Tax, Withholding & Income Tax',
    subtitle: 'The government is your silent business partner',
    art: 'tax',
    level: 'Advanced',
    minutes: 35,
    quote: 'In this world nothing can be said to be certain, except death and taxes. — Benjamin Franklin',
    goals: ['Explain how VAT/GST works with input tax credits', 'Record tax on sales, purchases and settlement', 'Compare VAT/GST with US-style sales tax', 'Record withholding taxes (TDS/WHT)', 'Understand current vs deferred income tax'],
    blocks: [
      { t: 'h', text: 'Indirect taxes: you’re the collector' },
      { t: 'p', html: '<b>VAT</b> (Value Added Tax — Europe, UK, Gulf, Africa…) and <b>GST</b> (Goods and Services Tax — India, Australia, Canada, Singapore…) are taxes on consumption. Businesses <b>collect</b> tax on sales (<b>output tax</b>), <b>reclaim</b> tax paid on purchases (<b>input tax</b>), and pay the difference to the government. The final consumer bears the cost.' },
      { t: 'widget', name: 'tax' },
      { t: 'sticky', html: 'VAT/GST collected is <b>not your revenue</b>. It’s the government’s money passing through your hands → a liability.' },
      { t: 'h3', text: 'The three entries' },
      { t: 'entry', title: 'Sale of $1,000 + 15% VAT', lines: [['Accounts Receivable', 1150, 0], ['Sales Revenue', 0, 1000], ['VAT Payable (output tax)', 0, 150]] },
      { t: 'entry', title: 'Purchase of $600 + 15% VAT', lines: [['Purchases / Expense', 600, 0], ['VAT Receivable (input tax)', 90, 0], ['Accounts Payable', 0, 690]] },
      { t: 'entry', title: 'Filing the return & paying the net', lines: [['VAT Payable', 150, 0], ['VAT Receivable', 0, 90], ['Bank', 0, 60]], narr: 'Net VAT due for the period' },
      { t: 'p', html: 'If input tax exceeds output tax (e.g., an exporter), you have a <b>refund</b> or carry-forward credit: a receivable from the government.' },
      {
        t: 'table',
        head: ['Term', 'Meaning'],
        rows: [
          ['Standard-rated', 'Normal rate applies (e.g., 5%, 15%, 18%, 20% — varies by country).'],
          ['Zero-rated', 'Taxable at 0% (often exports). You still <b>can</b> reclaim input tax.'],
          ['Exempt', 'Outside the tax (e.g., some financial or medical services). You <b>cannot</b> reclaim related input tax — it becomes a cost.'],
          ['Reverse charge', 'The buyer self-accounts for VAT (both output and input) — common for imported services and some B2B cross-border supplies.'],
          ['Tax point / time of supply', 'The date the tax becomes due (invoice, delivery or payment — rules vary).'],
          ['Cash-basis VAT', 'Some regimes let small businesses account for VAT when paid/received, not when invoiced.'],
        ],
      },
      { t: 'h3', text: 'India GST in one breath' },
      { t: 'p', html: 'Intra-state supply → <b>CGST + SGST</b> (split equally). Inter-state supply → <b>IGST</b>. Input tax credit can be used across them following set-off rules. Businesses file returns like GSTR-1 (outward supplies) and GSTR-3B (summary), and invoices may need e-invoicing (IRN) above thresholds.' },
      { t: 'h3', text: 'US sales tax: a different beast' },
      { t: 'compare', cols: [{ t: 'VAT / GST', color: 'blue', items: ['Charged at every stage of the chain', 'Businesses reclaim input tax', 'National (mostly) rates', 'Accounting: output − input'] }, { t: 'US sales tax', color: 'yellow', items: ['Charged only on the final retail sale', 'Resellers use exemption/resale certificates instead of reclaiming', 'State + county + city rates (thousands of jurisdictions)', 'Tax paid on business purchases is usually just a cost'] }] },

      { t: 'h', text: 'Withholding tax (TDS / WHT)' },
      { t: 'p', html: 'Some countries require the <b>payer</b> to deduct tax at source when paying certain suppliers (professional fees, rent, contractors, interest, non-residents) and remit it to the government. The supplier gets a credit against their own income tax.' },
      { t: 'entry', title: 'Max (payer) pays a $2,000 consultancy fee with 10% TDS', lines: [['Consultancy Expense', 2000, 0], ['TDS Payable', 0, 200], ['Bank', 0, 1800]] },
      { t: 'entry', title: 'The consultant (receiver) records it', lines: [['Bank', 1800, 0], ['TDS Receivable / Tax Credit', 200, 0], ['Accounts Receivable — Max’s Bikes', 0, 2000]] },
      { t: 'watch', html: 'A common mistake: the receiver treating the withheld $200 as a bad debt or a discount. It’s a <b>prepaid tax asset</b> they’ll offset against their income tax liability.' },

      { t: 'h', text: 'Income tax: current and deferred' },
      { t: 'p', html: '<b>Current tax</b> = taxable profit × tax rate, per tax law. But accounting profit and taxable profit differ:' },
      { t: 'list', items: ['<b>Permanent differences</b>: never reverse — fines and some entertainment are non-deductible; some income is tax-free.', '<b>Temporary differences</b>: timing only — e.g., tax law allows faster depreciation than the books. These create <b>deferred tax</b>.'] },
      { t: 'p', html: '<b>Example:</b> equipment cost $40,000. Book depreciation $10,000 in year 1; tax depreciation $20,000. At year-end, carrying amount $30,000 vs tax base $20,000 → taxable temporary difference $10,000. At 25%, a <b>deferred tax liability</b> of $2,500: you’ve paid less tax now and will pay more later.' },
      { t: 'entry', lines: [['Deferred Tax Expense', 2500, 0], ['Deferred Tax Liability', 0, 2500]] },
      { t: 'formula', html: 'Tax expense = Current tax + Deferred tax movement', note: 'So the P&L tax charge relates sensibly to accounting profit (IAS 12 / ASC 740).' },
      { t: 'p', html: '<b>Deferred tax assets</b> arise from deductible temporary differences (e.g., warranty provisions deductible only when paid) and unused tax losses — recognised only if future taxable profits are probable.' },
      {
        t: 'odoo',
        title: 'Taxes in Odoo',
        path: 'Accounting > Configuration > Taxes',
        html: '<ul><li>Each tax has a computation (percentage, fixed, group of taxes, division/price-included…), a <b>type</b> (Sales/Purchase), accounts for invoices and refunds, and <b>tax grids</b> that map amounts to boxes on the tax return.</li><li><b>Included in price</b> option for tax-inclusive pricing (B2C).</li><li><b>Cash-basis taxes</b> post to a transition account until payment.</li><li><b>Fiscal positions</b> automatically swap taxes/accounts by customer type or location (e.g., domestic 15% → export 0%, intra-EU B2B → reverse charge, intra-state CGST+SGST → inter-state IGST).</li><li><b>Tax Return</b> report (Accounting > Reporting) + a <b>closing entry</b> that moves balances to a tax payable/receivable account.</li><li>Withholding taxes are supported in several localizations (e.g., India TDS/TCS, LATAM).</li></ul>',
      },
      { t: 'bullets', items: ['VAT/GST: output tax − input tax = net payable; consumers bear the cost.', 'Tax collected is a liability, not revenue.', 'Zero-rated allows input credit; exempt doesn’t.', 'US sales tax is single-stage at retail.', 'Withholding tax: payer deducts and remits; receiver gets a tax credit asset.', 'Deferred tax arises from temporary differences between book and tax bases.'] },
    ],
    quiz: [
      { q: 'Output VAT for the period 9,000; input VAT 6,500. Net VAT payable?', o: ['15,500', '2,500', '6,500', '9,000'], a: 1, e: '9,000 − 6,500 = 2,500.' },
      { q: 'VAT collected on a sale is recorded as…', o: ['Revenue', 'A liability', 'An expense', 'Equity'], a: 1, e: 'It belongs to the government.' },
      { q: 'Which supply lets you reclaim related input tax?', o: ['Exempt', 'Zero-rated', 'Outside scope with no rights', 'Personal use'], a: 1, e: 'Zero-rated supplies are taxable at 0%, so input tax is recoverable.' },
      { q: 'Under US sales tax, a wholesaler buying for resale typically…', o: ['Pays tax and reclaims it', 'Provides a resale/exemption certificate', 'Pays double tax', 'Charges VAT'], a: 1, e: 'Sales tax is collected only on the final retail sale.' },
      { q: 'Paying a $5,000 fee with 10% withholding: bank payment is…', o: ['5,000', '5,500', '4,500', '500'], a: 2, e: '5,000 − 500 withheld.' },
      { q: 'Tax depreciation faster than book depreciation creates…', o: ['A deferred tax asset', 'A deferred tax liability', 'A permanent difference', 'No effect'], a: 1, e: 'Less tax now, more later.' },
      { q: 'In Odoo, what automatically maps taxes for export customers?', o: ['Payment terms', 'Fiscal positions', 'Analytic accounts', 'Journals'], a: 1, e: 'Fiscal positions swap taxes and accounts by partner/location.' },
    ],
    cards: [
      ['Output tax', 'VAT/GST charged on sales; a liability.'],
      ['Input tax', 'VAT/GST paid on purchases; reclaimable (asset).'],
      ['Zero-rated vs exempt', 'Zero-rated: 0% with input credit. Exempt: no VAT and no input credit.'],
      ['Reverse charge', 'Buyer accounts for the VAT instead of the supplier.'],
      ['Withholding tax (TDS)', 'Tax deducted by the payer at source and remitted to the government.'],
      ['Deferred tax liability', 'Tax payable in future due to taxable temporary differences.'],
      ['Fiscal position (Odoo)', 'Rule set that maps taxes/accounts based on partner type or location.'],
    ],
  });

  /* =============================== CH 20 =============================== */
  HF.addChapter({
    id: 'financial-analysis',
    part: 'p4',
    title: 'Financial Analysis & Ratios',
    subtitle: 'Reading between the lines of the statements',
    art: 'magnifier',
    level: 'Advanced',
    minutes: 30,
    quote: 'A ratio on its own is a number. A ratio compared to last year, a competitor or a target is a story.',
    goals: ['Perform horizontal and vertical analysis', 'Calculate and interpret liquidity, profitability, efficiency, solvency and market ratios', 'Use the DuPont model and cash conversion cycle', 'Know the limits of ratio analysis'],
    blocks: [
      { t: 'h', text: 'Horizontal & vertical analysis' },
      { t: 'compare', cols: [{ t: 'Horizontal (trend)', color: 'blue', items: ['Compare across periods', 'Revenue +12% vs last year; admin costs +30% → why?', 'Often shown as % change or index (base year = 100)'] }, { t: 'Vertical (common-size)', color: 'green', items: ['Each line as a % of a base', 'P&L lines as % of revenue; balance sheet lines as % of total assets', 'Lets you compare companies of different sizes'] }] },
      {
        t: 'table',
        caption: 'Max’s Bikes — common-size P&L',
        head: ['', '2025', '% rev', '2026', '% rev', 'Change'],
        rows: [
          ['Revenue', '200,000', '100%', '245,000', '100%', '+22.5%'],
          ['COGS', '124,000', '62%', '147,000', '60%', '+18.5%'],
          ['Gross profit', '76,000', '38%', '98,000', '40%', '+28.9%'],
          ['Operating expenses', '50,000', '25%', '58,000', '23.7%', '+16%'],
          ['Operating profit', '26,000', '13%', '40,000', '16.3%', '+53.8%'],
        ],
      },
      { t: 'brain', html: 'Operating profit grew more than twice as fast as revenue. Which two things in the table explain that? (Hint: look at the % of revenue columns.) That effect is called <b>operating leverage</b>.' },

      { t: 'h', text: 'The ratio toolkit' },
      {
        t: 'table',
        head: ['Family', 'Ratio', 'Formula', 'Tells you'],
        rows: [
          ['💧 Liquidity', 'Current ratio', 'Current assets ÷ current liabilities', 'Short-term solvency'],
          ['', 'Quick (acid-test)', '(Cash + receivables + marketable securities) ÷ current liabilities', 'Liquidity without inventory'],
          ['💰 Profitability', 'Gross margin', 'Gross profit ÷ revenue', 'Pricing power & production efficiency'],
          ['', 'Net margin', 'Net profit ÷ revenue', 'Overall profitability'],
          ['', 'ROA', 'Net profit ÷ average total assets', 'How well assets generate profit'],
          ['', 'ROE', 'Net profit ÷ average equity', 'Return to owners'],
          ['', 'ROCE', 'EBIT ÷ (equity + non-current liabilities)', 'Return on all long-term capital'],
          ['⚙️ Efficiency', 'Inventory turnover / DIO', 'COGS ÷ avg inventory; 365 ÷ turnover', 'How fast stock sells'],
          ['', 'DSO', 'Receivables ÷ revenue × 365', 'How fast customers pay'],
          ['', 'DPO', 'Payables ÷ COGS (or purchases) × 365', 'How long you take to pay suppliers'],
          ['', 'Asset turnover', 'Revenue ÷ average total assets', 'Sales generated per $ of assets'],
          ['🏋️ Solvency', 'Debt-to-equity', 'Total liabilities (or debt) ÷ equity', 'Financial risk / leverage'],
          ['', 'Interest coverage', 'EBIT ÷ interest expense', 'Ability to service debt'],
          ['📈 Market', 'EPS', 'Profit to ordinary shareholders ÷ shares', 'Profit per share'],
          ['', 'P/E', 'Share price ÷ EPS', 'How the market values earnings'],
          ['', 'Dividend yield', 'Dividend per share ÷ share price', 'Cash return to investors'],
        ],
      },
      { t: 'widget', name: 'ratios' },

      { t: 'h', text: 'DuPont: taking ROE apart' },
      { t: 'formula', html: 'ROE = Net margin × Asset turnover × Equity multiplier', note: '(Profit/Revenue) × (Revenue/Assets) × (Assets/Equity)' },
      { t: 'p', html: 'Two companies with the same 15% ROE can be very different: a luxury brand (high margin, low turnover) vs a supermarket (thin margin, huge turnover) vs a bank (high leverage). DuPont shows <i>where</i> the return comes from — and whether it relies on risky borrowing.' },
      { t: 'pencil', items: [{ q: 'Net margin 5%, asset turnover 2.0, assets/equity 2.5. ROE?', input: true, a: '5% × 2.0 × 2.5 = <b>25%</b>.' }] },

      { t: 'h', text: 'Cash conversion cycle' },
      { t: 'formula', html: 'CCC = DIO + DSO − DPO', note: 'Days between paying suppliers and collecting from customers.' },
      { t: 'p', html: 'Max: inventory sits 57 days, customers pay in 22, suppliers are paid in 30 → CCC = 49 days of cash tied up. Cut inventory days by 15 and you free up ~15 days of COGS in cash. Some retailers (and Amazon, famously) have <b>negative</b> CCCs: customers pay before suppliers are paid.' },

      { t: 'h', text: 'Limits & red flags' },
      { t: 'cards', cols: 3, items: [{ icon: '🪞', t: 'Window dressing', d: 'Year-end tricks (delay payments, rush sales) make ratios look better on one day.' }, { icon: '🍎🍊', t: 'Different policies', d: 'FIFO vs AVCO, revaluation vs cost, lease accounting — compare like with like.' }, { icon: '📅', t: 'Seasonality', d: 'A bike shop in March vs November? Use averages and same-period comparisons.' }, { icon: '🧮', t: 'Profit without cash', d: 'Rising profit but falling operating cash flow → check receivables and inventory.' }, { icon: '🔁', t: 'One-offs', d: 'Strip out gains on asset sales, restructuring, impairments to see the underlying trend.' }, { icon: '🎯', t: 'Benchmarks', d: 'A ratio means nothing alone: compare to history, peers, industry and targets.' }] },
      { t: 'odoo', path: 'Accounting > Reporting > Executive Summary', html: 'Odoo’s <b>Executive Summary</b> report shows key figures and ratios (e.g., gross/net margin, current ratio, DSO/DPO, return on investment) with period comparisons. You can also build custom reports and pivot views on journal items, or export to spreadsheets for deeper analysis.' },
      { t: 'bullets', items: ['Horizontal = trends over time; vertical = % of a base.', 'Ratio families: liquidity, profitability, efficiency, solvency, market.', 'DuPont splits ROE into margin, turnover and leverage.', 'CCC = DIO + DSO − DPO: shorter is better for cash.', 'Always compare ratios against a benchmark and check cash flow.'] },
    ],
    quiz: [
      { q: 'Current assets 120k (inventory 50k), current liabilities 80k. Quick ratio (cash + receivables only)?', o: ['1.5', '0.875', '2.4', '0.63'], a: 1, e: '(120 − 50) ÷ 80 = 0.875.' },
      { q: 'Net margin 10%, asset turnover 1.5, equity multiplier 2. ROE?', o: ['13.5%', '30%', '20%', '15%'], a: 1, e: '10% × 1.5 × 2 = 30%.' },
      { q: 'DIO 40, DSO 35, DPO 25. Cash conversion cycle?', o: ['100', '50', '30', '−50'], a: 1, e: '40 + 35 − 25 = 50 days.' },
      { q: 'Vertical analysis of a P&L expresses each line as a % of…', o: ['Total assets', 'Revenue', 'Net profit', 'Last year'], a: 1, e: 'Common-size P&L uses revenue as the base.' },
      { q: 'Interest coverage of 1.2× suggests…', o: ['Very safe debt levels', 'Thin ability to pay interest', 'High liquidity', 'High dividends'], a: 1, e: 'EBIT barely covers interest.' },
      { q: 'Profit is rising but operating cash flow falling. First places to look?', o: ['Share capital', 'Receivables and inventory', 'Goodwill', 'Dividends'], a: 1, e: 'Working capital can absorb cash.' },
    ],
    cards: [
      ['Current ratio', 'Current assets ÷ current liabilities.'],
      ['Quick ratio', '(Cash + receivables + marketable securities) ÷ current liabilities.'],
      ['ROE', 'Net profit ÷ average equity.'],
      ['DuPont', 'ROE = net margin × asset turnover × equity multiplier.'],
      ['Cash conversion cycle', 'DIO + DSO − DPO.'],
      ['Interest coverage', 'EBIT ÷ interest expense.'],
      ['Common-size statements', 'Statements with each line as a % of revenue or total assets.'],
    ],
  });

  /* =============================== CH 21 =============================== */
  HF.addChapter({
    id: 'cost-accounting',
    part: 'p4',
    title: 'Cost Accounting & CVP',
    subtitle: 'What does it really cost — and how many do we need to sell?',
    art: 'factory',
    level: 'Advanced',
    minutes: 35,
    quote: 'Know your costs and you know your options.',
    goals: ['Classify costs (direct/indirect, fixed/variable, product/period, relevant/sunk)', 'Apply job, process and activity-based costing', 'Compute overhead absorption rates', 'Use contribution margin, break-even and margin of safety', 'Contrast absorption and marginal costing'],
    blocks: [
      { t: 'h', text: 'Costs come in many flavours' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch21-fv',
          title: 'Fixed or variable? (for Max’s bike assembly)',
          bins: [
            { id: 'F', label: 'Fixed', color: '#2e86ab' },
            { id: 'V', label: 'Variable', color: '#e4572e' },
            { id: 'M', label: 'Mixed (semi-variable)', color: '#c08a00' },
          ],
          items: [
            { text: 'Workshop rent', bin: 'F' },
            { text: 'Bike frames used', bin: 'V' },
            { text: 'Sales commission per bike', bin: 'V' },
            { text: 'Manager’s salary', bin: 'F' },
            { text: 'Electricity (fixed charge + usage)', bin: 'M' },
            { text: 'Insurance premium', bin: 'F' },
            { text: 'Packaging per bike', bin: 'V' },
            { text: 'Phone plan: base + per-minute', bin: 'M' },
            { text: 'Straight-line depreciation of tools', bin: 'F' },
          ],
        },
      },
      {
        t: 'table',
        head: ['Classification', 'Meaning', 'Example'],
        rows: [
          ['Direct vs indirect', 'Traceable to a product (or not)', 'Frame = direct; workshop cleaning = indirect (overhead)'],
          ['Fixed vs variable', 'Behaviour as volume changes', 'Rent fixed; materials variable'],
          ['Product vs period', 'Goes into inventory (then COGS) vs expensed when incurred', 'Factory labour vs marketing'],
          ['Relevant vs sunk', 'Future costs that differ between options vs past costs', 'Last year’s R&D is sunk'],
          ['Opportunity cost', 'Benefit given up by choosing an alternative', 'Using the workshop for repairs instead of renting it out'],
          ['Controllable vs uncontrollable', 'Within a manager’s power to influence', 'Overtime (controllable) vs head-office allocation'],
        ],
      },

      { t: 'h', text: 'Costing systems' },
      { t: 'cards', cols: 3, items: [{ icon: '🧰', t: 'Job costing', d: 'Unique jobs or batches: custom bikes, construction, consulting projects. Track materials, labour and overhead per job.', color: 'blue' }, { icon: '🧪', t: 'Process costing', d: 'Continuous identical units: paint, drinks, cement. Average cost per <b>equivalent unit</b> per process.', color: 'green' }, { icon: '🧩', t: 'Activity-based costing (ABC)', d: 'Assign overhead using many cost drivers (setups, inspections, orders) instead of one volume measure. More accurate for diverse products.', color: 'purple' }] },
      { t: 'h3', text: 'Overhead absorption' },
      { t: 'formula', html: 'Overhead absorption rate = Budgeted overhead ÷ Budgeted activity', note: 'e.g., $120,000 ÷ 8,000 labour hours = $15 per labour hour' },
      { t: 'p', html: 'A custom bike uses $600 materials, 10 labour hours at $25, and absorbs 10 × $15 overhead. <b>Job cost</b> = 600 + 250 + 150 = <b>$1,000</b>. At year-end, if actual overhead differs from absorbed overhead, the difference is <b>under-</b> or <b>over-absorbed</b> overhead (usually adjusted through COGS).' },
      { t: 'pencil', items: [{ q: 'Budgeted overhead $90,000, budgeted machine hours 6,000. Actual: overhead $95,000, machine hours 6,500. Over- or under-absorbed?', input: true, a: 'Rate $15/hr. Absorbed 6,500 × 15 = $97,500 vs actual $95,000 → <b>over-absorbed by $2,500</b> (credit to P&L / reduce COGS).' }] },

      { t: 'h', text: 'Cost-volume-profit (CVP)' },
      { t: 'formula', html: 'Contribution margin = Price − Variable cost per unit', note: 'Each sale “contributes” this much towards fixed costs, then profit.' },
      { t: 'formula', html: 'Break-even units = Fixed costs ÷ Contribution margin per unit' },
      { t: 'formula', html: 'Target units = (Fixed costs + Target profit) ÷ CM per unit' },
      { t: 'widget', name: 'breakeven' },
      { t: 'p', html: '<b>Margin of safety</b> = (expected sales − break-even sales) ÷ expected sales. It tells you how far sales can fall before you make a loss. <b>Operating leverage</b> = contribution ÷ operating profit — high fixed costs mean profit swings hard with volume.' },

      { t: 'h', text: 'Absorption vs marginal costing' },
      { t: 'compare', cols: [{ t: 'Absorption (full) costing', color: 'blue', items: ['Inventory includes fixed production overhead', 'Required for external reporting (IFRS/GAAP) and tax', 'Producing more than you sell can boost profit (overhead parked in inventory)'] }, { t: 'Marginal (variable) costing', color: 'green', items: ['Inventory includes only variable production costs', 'Fixed overhead expensed in the period', 'Better for decisions; profit follows sales'] }] },
      { t: 'formula', html: 'Profit difference = Change in inventory units × Fixed overhead per unit' },
      { t: 'h3', text: 'Relevant costing: make or buy?' },
      { t: 'p', html: 'Max can make wheels in-house (variable cost $40, plus $8 of fixed overhead allocated per wheel that won’t disappear) or buy them at $45. Relevant cost of making = $40 (only the avoidable cost). Buying costs $45 → <b>keep making</b>, unless the freed capacity could earn more than $5 per wheel elsewhere (opportunity cost).' },
      { t: 'odoo', html: 'Odoo <b>Manufacturing</b> computes product cost from bills of materials, work centre costs per hour and operations; <b>analytic accounting</b> tracks costs per job/project; and the <b>product cost</b> (standard/AVCO/FIFO) flows into inventory valuation and COGS.' },
      { t: 'bullets', items: ['Classify costs by traceability, behaviour, timing and relevance.', 'Job costing for unique jobs; process costing for continuous output; ABC for complex overhead.', 'OAR = budgeted overhead ÷ budgeted activity; differences are under/over-absorbed.', 'Break-even = fixed costs ÷ contribution margin per unit.', 'Absorption costing for reporting; marginal costing for decisions.', 'Ignore sunk costs; include opportunity costs.'] },
    ],
    quiz: [
      { q: 'Price $50, variable cost $30, fixed costs $40,000. Break-even units?', o: ['800', '1,333', '2,000', '4,000'], a: 2, e: '40,000 ÷ 20 = 2,000.' },
      { q: 'Which is a sunk cost?', o: ['Next month’s rent', 'Market research already paid for', 'Raw materials to be bought', 'Opportunity cost'], a: 1, e: 'Past costs that can’t be changed are irrelevant to decisions.' },
      { q: 'Process costing is best for…', o: ['Custom furniture', 'Oil refining', 'Law firm cases', 'Construction projects'], a: 1, e: 'Continuous, identical output.' },
      { q: 'Under absorption costing, when production exceeds sales, profit is ___ than under marginal costing.', o: ['Lower', 'Higher', 'The same', 'Zero'], a: 1, e: 'Some fixed overhead is carried forward in inventory.' },
      { q: 'Absorbed overhead $50,000; actual overhead $53,000. This is…', o: ['Over-absorbed $3,000', 'Under-absorbed $3,000', 'Exactly absorbed', 'A sunk cost'], a: 1, e: 'Actual exceeded absorbed.' },
      { q: 'Expected sales 5,000 units, break-even 4,000. Margin of safety?', o: ['20%', '25%', '80%', '1,000%'], a: 0, e: '(5,000 − 4,000) ÷ 5,000 = 20%.' },
    ],
    cards: [
      ['Contribution margin', 'Price − variable cost per unit.'],
      ['Break-even point', 'Fixed costs ÷ contribution margin per unit.'],
      ['Margin of safety', '(Expected − break-even sales) ÷ expected sales.'],
      ['Overhead absorption rate', 'Budgeted overhead ÷ budgeted activity level.'],
      ['Activity-based costing', 'Allocating overhead using multiple activity cost drivers.'],
      ['Relevant cost', 'Future cash cost that differs between alternatives.'],
      ['Marginal costing', 'Only variable production costs in inventory; fixed overhead expensed.'],
    ],
  });

  /* =============================== CH 22 =============================== */
  HF.addChapter({
    id: 'budgeting',
    part: 'p4',
    title: 'Budgeting, Variances & Performance',
    subtitle: 'Plan the year, then play detective when reality disagrees',
    art: 'chart',
    level: 'Advanced',
    minutes: 30,
    quote: 'A budget is telling your money where to go instead of wondering where it went.',
    goals: ['Build a master budget in the right order', 'Prepare a cash budget', 'Compare static and flexible budgets', 'Compute price/quantity variances', 'Use responsibility centres and KPIs'],
    blocks: [
      { t: 'h', text: 'The master budget waterfall' },
      { t: 'flow', items: [{ t: 'Sales budget', c: '#fff3a8' }, { t: 'Production / purchases', c: '#bfe0f2' }, { t: 'Materials · Labour · Overhead', c: '#bfe0f2' }, { t: 'COGS & operating expenses', c: '#f7c6d0' }, { t: 'Cash budget', c: '#b5e3c4' }, { t: 'Budgeted P&L & balance sheet', c: '#d9c7f0' }] },
      { t: 'p', html: 'Everything starts with <b>sales</b> — usually the hardest number to forecast. Production = sales + desired closing inventory − opening inventory.' },
      { t: 'pencil', items: [{ q: 'Budgeted sales 1,000 bikes. Opening inventory 120, desired closing inventory 150. Bikes to purchase?', input: true, a: '1,000 + 150 − 120 = <b>1,030</b>.' }] },
      { t: 'h3', text: 'The cash budget' },
      {
        t: 'table',
        caption: 'Max’s Bikes — Q1 cash budget',
        head: ['', 'Jan', 'Feb', 'Mar'],
        rows: [
          ['Opening cash', '18,000', '14,700', '11,900'],
          ['+ Cash sales (40% of sales)', '8,000', '10,000', '16,000'],
          ['+ Collections of credit sales (60%, one month later)', '14,000', '12,000', '15,000'],
          ['− Supplier payments', '(16,000)', '(15,500)', '(24,000)'],
          ['− Wages & rent', '(9,300)', '(9,300)', '(9,300)'],
          ['− New workshop tools', '', '', '(12,000)'],
          { _cls: 'tot', cells: ['Closing cash', '14,700', '11,900', '<b class="neg">(2,400)</b>'] },
        ],
      },
      { t: 'say', who: 'max', html: 'March goes negative! The year’s profit looks fine, but I’ll run out of cash before spring?' },
      { t: 'say', who: 'penny', right: true, html: 'That’s exactly why we budget cash. Options: arrange an overdraft now, delay the tools to April, offer a small discount for early payment, or negotiate longer supplier terms. Seeing it in January beats discovering it in March!' },

      { t: 'h', text: 'Static vs flexible budgets' },
      { t: 'p', html: 'Budget: 1,000 bikes, materials $200 each = $200,000. Actual: 1,200 bikes sold, materials $228,000. Bad news, $28,000 over budget? Not so fast. A <b>flexible budget</b> restates the budget at <b>actual volume</b>: 1,200 × $200 = $240,000. Against that, materials were actually <b>$12,000 favourable</b>.' },
      { t: 'watch', html: 'Never judge variable costs against a static budget when volume changed. You’ll punish managers for selling more!' },
      { t: 'h', text: 'Standard costing & variances' },
      { t: 'widget', name: 'variance' },
      {
        t: 'table',
        head: ['Variance', 'Formula', 'Typical causes'],
        rows: [
          ['Material price', '(AP − SP) × AQ', 'Supplier prices, discounts, quality grade, rush orders'],
          ['Material usage', '(AQ − SQ) × SP', 'Waste, poor quality material, skill level'],
          ['Labour rate', '(AR − SR) × AH', 'Overtime, pay rises, skill mix'],
          ['Labour efficiency', '(AH − SH) × SR', 'Training, machine breakdowns, morale'],
          ['Sales volume', '(Actual − budget units) × standard margin', 'Demand, marketing, competition'],
          ['Sales price', '(Actual − standard price) × actual units', 'Discounting, price changes'],
        ],
      },
      { t: 'p', html: 'A variance is <b>favourable (F)</b> if it increases profit, <b>adverse/unfavourable (A/U)</b> if it reduces it.' },

      { t: 'h', text: 'Responsibility & KPIs' },
      { t: 'cards', cols: 4, items: [{ icon: '💸', t: 'Cost centre', d: 'Manager controls costs (e.g., workshop). KPI: cost vs budget.' }, { icon: '💵', t: 'Revenue centre', d: 'Manager controls sales (e.g., sales team). KPI: revenue, margin.' }, { icon: '📈', t: 'Profit centre', d: 'Controls both (e.g., a store). KPI: profit, margin.' }, { icon: '🏢', t: 'Investment centre', d: 'Also controls assets (e.g., a division). KPI: ROI, residual income, EVA.' }] },
      { t: 'p', html: 'The <b>balanced scorecard</b> adds non-financial perspectives — customer, internal processes, learning & growth — so managers don’t chase short-term profit at the expense of the future. Modern approaches include <b>rolling forecasts</b> (always looking 12–18 months ahead) and <b>zero-based budgeting</b> (justify every cost from zero).' },
      { t: 'odoo', title: 'Budgets in Odoo', html: 'Odoo Enterprise lets you define <b>budgets</b> per analytic account (department, project, store) and compare planned vs actual amounts — achieved % at a glance. Combined with <b>analytic plans</b> and pivot/spreadsheet reporting, you get a live budget-vs-actual dashboard. (Menu location varies by version: Accounting > Accounting/Configuration > Budgets.)' },
      { t: 'bullets', items: ['Master budget flows from sales → production → costs → cash → budgeted statements.', 'Cash budgets reveal funding gaps early.', 'Flexible budgets restate the plan at actual volume.', 'Price and quantity variances explain cost differences.', 'Responsibility centres and KPIs match measures to what managers control.'] },
    ],
    quiz: [
      { q: 'The starting point of a master budget is usually the…', o: ['Cash budget', 'Sales budget', 'Balance sheet', 'Capex budget'], a: 1, e: 'Most other budgets depend on expected sales.' },
      { q: 'Sales 500 units, opening inventory 80, desired closing 100. Units to produce?', o: ['480', '520', '500', '680'], a: 1, e: '500 + 100 − 80 = 520.' },
      { q: 'AQ 1,100 kg, SQ 1,000 kg, SP $5. Material usage variance?', o: ['$500 F', '$500 A', '$5,500 A', '$100 A'], a: 1, e: '(1,100 − 1,000) × 5 = 500 adverse.' },
      { q: 'A flexible budget is prepared at…', o: ['Budgeted volume', 'Actual volume', 'Last year’s volume', 'Maximum capacity'], a: 1, e: 'It adjusts the plan to the activity actually achieved.' },
      { q: 'An investment centre manager is typically evaluated on…', o: ['Revenue only', 'Costs only', 'ROI or residual income', 'Headcount'], a: 2, e: 'They control profit and invested assets.' },
      { q: 'A favourable price variance with an adverse usage variance might suggest…', o: ['Cheaper, lower-quality materials', 'Excellent staff training', 'Higher sales', 'Lower rent'], a: 0, e: 'Cheap materials can increase waste.' },
    ],
    cards: [
      ['Master budget', 'Integrated set of operating and financial budgets for a period.'],
      ['Cash budget', 'Forecast of cash receipts, payments and balances.'],
      ['Flexible budget', 'Budget adjusted to the actual level of activity.'],
      ['Material price variance', '(Actual price − standard price) × actual quantity.'],
      ['Material usage variance', '(Actual qty − standard qty) × standard price.'],
      ['Balanced scorecard', 'Performance framework: financial, customer, internal process, learning & growth.'],
    ],
  });

  /* =============================== CH 23 =============================== */
  HF.addChapter({
    id: 'revenue-leases',
    part: 'p4',
    title: 'Revenue Recognition & Leases',
    subtitle: 'IFRS 15, IFRS 16 and the time value of money',
    art: 'handshake',
    level: 'Advanced',
    minutes: 35,
    quote: 'Revenue is the single most important number investors look at. That’s why it has its own five-step rulebook.',
    goals: ['Apply the IFRS 15 / ASC 606 five-step model', 'Handle bundles, variable consideration and principal-vs-agent', 'Use present value in accounting', 'Account for leases as a lessee under IFRS 16 (and know how ASC 842 differs)'],
    blocks: [
      { t: 'h', text: 'The five-step model' },
      { t: 'steps', items: [{ t: 'Identify the contract', d: 'An enforceable agreement with commercial substance, approved, with identifiable rights and payment terms, and probable collection.' }, { t: 'Identify performance obligations', d: 'Each distinct promise: a good or service the customer can benefit from on its own and that’s separately identifiable.' }, { t: 'Determine the transaction price', d: 'Fixed amounts plus <b>variable consideration</b> (discounts, rebates, bonuses — constrained so a big reversal is unlikely), adjusted for significant financing components and non-cash consideration.' }, { t: 'Allocate the price', d: 'In proportion to <b>stand-alone selling prices</b> (SSP).' }, { t: 'Recognise revenue', d: 'When (point in time) or as (over time) each obligation is satisfied — i.e., when control transfers.' }] },
      { t: 'widget', name: 'revrec' },
      { t: 'h3', text: 'Over time or at a point in time?' },
      { t: 'p', html: 'Revenue is recognised <b>over time</b> if any of these is true: (1) the customer receives and consumes the benefit as you perform (cleaning, subscriptions), (2) you create/enhance an asset the customer controls (building on their land), or (3) the asset has no alternative use to you <i>and</i> you have an enforceable right to payment for work done so far. Otherwise, at the <b>point in time</b> control transfers (indicators: legal title, physical possession, risks & rewards, acceptance, right to payment).' },
      { t: 'cards', cols: 3, items: [{ icon: '🎟️', t: 'Principal vs agent', d: 'Do you control the good before it goes to the customer? Principal → gross revenue. Agent (marketplace, travel agent) → only your commission.', color: 'blue' }, { icon: '🎁', t: 'Loyalty points & warranties', d: 'Points = separate obligation (defer part of the price). Assurance warranties = provision; extended/service warranties = separate obligation.', color: 'yellow' }, { icon: '📄', t: 'Contract balances', d: '<b>Contract asset</b>: performed but right to payment is conditional. <b>Receivable</b>: unconditional. <b>Contract liability</b>: paid before performing.', color: 'green' }] },
      { t: 'pencil', items: [{ q: 'Max sells a bike ($900 SSP) with a free 1-year service plan ($100 SSP) for $950. How much revenue on day 1?', input: true, a: 'Allocate $950 by SSP: bike 900/1,000 × 950 = <b>$855</b> on delivery; service $95 recognised over 12 months (~$7.92/month).' }] },

      { t: 'h', text: 'Time value of money (you’ll need it)' },
      { t: 'formula', html: 'PV = FV ÷ (1 + r)ⁿ', note: 'Present value of a future amount. Annuity PV = payment × [1 − (1 + r)⁻ⁿ] ÷ r' },
      { t: 'widget', name: 'tvm' },
      { t: 'p', html: 'Discounting shows up all over modern accounting: leases, long-term provisions (e.g., decommissioning), bonds, impairment (value in use), pensions and significant financing components in revenue.' },

      { t: 'h', text: 'Leases under IFRS 16 (lessee)' },
      { t: 'p', html: 'Before 2019 many leases were “off balance sheet”. Now a lessee recognises nearly all leases on the balance sheet:' },
      { t: 'list', items: ['<b>Lease liability</b> = PV of future lease payments, discounted at the rate implicit in the lease (or the incremental borrowing rate).', '<b>Right-of-use (ROU) asset</b> = lease liability + initial direct costs + prepayments + restoration costs − incentives.', 'Then: depreciate the ROU asset (usually straight-line) and unwind interest on the liability (effective interest).', 'Exemptions: short-term leases (≤12 months) and low-value assets (e.g., laptops) can be expensed straight-line.'] },
      { t: 'p', html: '<b>Example:</b> Max leases a shop for 3 years, $10,000 per year paid at the end of each year, incremental borrowing rate 5%. PV = 10,000 × 2.7232 = <b>$27,232</b>.' },
      { t: 'entry', title: 'Commencement', lines: [['Right-of-use Asset', 27232, 0], ['Lease Liability', 0, 27232]] },
      {
        t: 'table',
        caption: 'Lease liability schedule',
        head: ['Year', 'Opening', 'Interest 5%', 'Payment', 'Closing'],
        rows: [
          ['1', '27,232', '1,362', '(10,000)', '18,594'],
          ['2', '18,594', '930', '(10,000)', '9,524'],
          ['3', '9,524', '476', '(10,000)', '0'],
        ],
      },
      { t: 'entry', title: 'Year 1', lines: [['Interest Expense', 1362, 0], ['Lease Liability', 8638, 0], ['Bank', 0, 10000]] },
      { t: 'entry', lines: [['Depreciation — ROU Asset', 9077, 0], ['Accumulated Depreciation — ROU', 0, 9077]], narr: '27,232 ÷ 3 years' },
      { t: 'p', html: 'Year 1 P&L charge: 1,362 + 9,077 = <b>$10,439</b> — more than the $10,000 cash paid. Lease expense is <b>front-loaded</b> under IFRS 16. EBITDA rises (rent is gone from operating expenses), and lease principal payments move to <b>financing</b> cash flows.' },
      { t: 'compare', cols: [{ t: 'IFRS 16 (lessee)', color: 'blue', items: ['Single model: all leases → depreciation + interest', 'Front-loaded expense'] }, { t: 'US GAAP ASC 842 (lessee)', color: 'yellow', items: ['Also on balance sheet, but two types', '<b>Finance leases</b>: like IFRS 16', '<b>Operating leases</b>: single straight-line lease cost in operating expenses'] }] },
      { t: 'odoo', html: 'Odoo handles revenue timing through <b>deferred revenue</b> on invoice lines (start/end dates), <b>subscriptions</b> (recurring invoicing) and down payments/milestones on sales orders. IFRS 16 lease schedules are typically set up as an <b>asset</b> (ROU) with its depreciation board plus a manual/loan-style schedule for the liability — or via a localization/add-on.' },
      { t: 'bullets', items: ['Five steps: contract → obligations → price → allocate → recognise.', 'Allocate by stand-alone selling prices.', 'Over time vs point in time depends on control transfer criteria.', 'Principal reports gross revenue; agent reports net commission.', 'IFRS 16: lease liability = PV of payments; ROU asset depreciated; interest unwound.', 'ASC 842 keeps an operating-lease straight-line expense pattern.'] },
    ],
    quiz: [
      { q: 'Step 4 of IFRS 15 allocates the transaction price based on…', o: ['Cost of each item', 'Stand-alone selling prices', 'Equal shares', 'Cash received'], a: 1, e: 'Relative SSP allocation.' },
      { q: 'An online marketplace that never controls the goods should report…', o: ['Gross sales value', 'Only its commission', 'Nothing', 'Cost of sales'], a: 1, e: 'It is an agent.' },
      { q: 'Cash received before performance is a…', o: ['Contract asset', 'Contract liability', 'Receivable', 'Revenue'], a: 1, e: 'You owe performance.' },
      { q: 'PV of $1,000 in 2 years at 10%?', o: ['$826', '$1,210', '$800', '$909'], a: 0, e: '1,000 ÷ 1.21 = 826.' },
      { q: 'Under IFRS 16, the lease liability is initially measured at…', o: ['Total undiscounted payments', 'PV of lease payments', 'Fair value of the building', 'Zero'], a: 1, e: 'Discounted lease payments.' },
      { q: 'Compared with straight-line rent, IFRS 16 expense in early years is…', o: ['Lower', 'Higher (front-loaded)', 'Identical', 'Zero'], a: 1, e: 'Interest is highest early on.' },
      { q: 'Which lease can be expensed straight-line under IFRS 16?', o: ['10-year building lease', '6-month equipment rental', 'Aircraft lease', 'Any lease above $1m'], a: 1, e: 'Short-term (≤12 months) exemption.' },
    ],
    cards: [
      ['IFRS 15 five steps', 'Contract, performance obligations, transaction price, allocation, recognition.'],
      ['Performance obligation', 'A distinct promise to transfer a good or service.'],
      ['Stand-alone selling price', 'Price at which an item would be sold separately.'],
      ['Contract liability', 'Obligation to transfer goods/services for which consideration was received.'],
      ['Right-of-use asset', 'Lessee’s asset representing the right to use a leased item.'],
      ['Lease liability', 'PV of unpaid lease payments.'],
      ['Present value', 'Future amount discounted: FV ÷ (1 + r)ⁿ.'],
    ],
  });

  /* =============================== CH 24 =============================== */
  HF.addChapter({
    id: 'groups-fx',
    part: 'p4',
    title: 'Group Accounts & Foreign Currency',
    subtitle: 'When one company owns another — and when money crosses borders',
    art: 'globe',
    level: 'Advanced',
    minutes: 35,
    quote: 'A group is one economic entity wearing many legal hats.',
    goals: ['Explain control, subsidiaries, associates and joint arrangements', 'Calculate goodwill and non-controlling interest', 'Eliminate intercompany transactions and unrealised profit', 'Account for foreign currency transactions and translation'],
    blocks: [
      { t: 'h', text: 'Who’s in the family?' },
      {
        t: 'table',
        head: ['Relationship', 'Typical holding', 'Test', 'Accounting'],
        rows: [
          ['Subsidiary', '> 50%', '<b>Control</b>: power + variable returns + ability to use power (IFRS 10)', 'Full consolidation, line by line'],
          ['Associate', '20%–50%', '<b>Significant influence</b> (IAS 28)', 'Equity method: one line, share of profit'],
          ['Joint venture', 'Shared', '<b>Joint control</b>, rights to net assets (IFRS 11)', 'Equity method'],
          ['Joint operation', 'Shared', 'Joint control, rights to assets/obligations for liabilities', 'Own share of assets, liabilities, revenue, expenses'],
          ['Simple investment', '< 20%', 'No influence', 'Financial instrument (IFRS 9) at fair value'],
        ],
      },
      { t: 'sticky', html: 'Percentages are just hints. <b>Control</b> can exist with 40% (e.g., other holders are scattered) or be absent at 60% (e.g., a contract gives power to someone else).' },

      { t: 'h', text: 'Consolidation step by step' },
      { t: 'steps', items: [{ t: 'Add everything up', d: 'Parent + 100% of each subsidiary’s assets, liabilities, income and expenses, line by line (even if you own 80%).' }, { t: 'Eliminate the investment', d: 'Remove the parent’s “Investment in Sub” against the subsidiary’s equity at acquisition, recognising goodwill.' }, { t: 'Recognise NCI', d: 'Non-controlling interest = the outside shareholders’ share of the subsidiary’s net assets, shown within equity.' }, { t: 'Eliminate intra-group items', d: 'Intercompany balances, sales/purchases, dividends, and unrealised profit in inventory or assets.' }, { t: 'Uniform policies & dates', d: 'Align accounting policies and reporting dates across the group.' }] },
      { t: 'formula', html: 'Goodwill = Consideration + NCI − Fair value of net assets acquired' },
      { t: 'p', html: '<b>Example:</b> Max Holdings buys 80% of Wheelco for $900,000. Wheelco’s identifiable net assets at fair value: $1,000,000. NCI measured at its share of net assets (20% × 1,000,000 = $200,000). Goodwill = 900,000 + 200,000 − 1,000,000 = <b>$100,000</b>. (IFRS also allows NCI at fair value — “full goodwill”.) A negative result is a <b>bargain purchase gain</b> (after re-checking the numbers!).' },
      { t: 'h3', text: 'Unrealised profit' },
      { t: 'p', html: 'Wheelco sells wheels to the parent for $50,000 that cost $40,000. At year-end, the parent still holds a quarter of them. From the group’s view, nothing was sold to outsiders for that quarter, so remove the profit: 25% × $10,000 = $2,500.' },
      { t: 'entry', title: 'Consolidation adjustments', lines: [['Revenue (intercompany)', 50000, 0], ['Cost of Sales', 0, 50000]], narr: 'Eliminate intra-group sale' },
      { t: 'entry', lines: [['Cost of Sales', 2500, 0], ['Inventory', 0, 2500]], narr: 'Remove unrealised profit in closing inventory' },
      { t: 'h3', text: 'The equity method' },
      { t: 'p', html: 'Investment starts at cost, then increases by your share of the associate’s profit and decreases by dividends received. One line on the balance sheet (“Investment in associate”) and one line in the P&L (“Share of profit of associates”).' },

      { t: 'h', text: 'Foreign currency transactions' },
      { t: 'list', items: ['Every entity has a <b>functional currency</b> — the currency of its primary economic environment.', 'Record foreign transactions at the <b>spot rate</b> on the transaction date.', 'At each reporting date, retranslate <b>monetary items</b> (cash, receivables, payables, loans) at the <b>closing rate</b> → <b>unrealised</b> exchange gains/losses in P&L.', '<b>Non-monetary items</b> at historical cost (inventory, PPE, prepaid) are not retranslated.', 'On settlement, differences become <b>realised</b> gains/losses.'] },
      { t: 'widget', name: 'fx' },
      { t: 'h3', text: 'Translating a foreign subsidiary' },
      { t: 'p', html: 'To consolidate Wheelco Europe (functional currency EUR) into a USD group: assets and liabilities at the <b>closing rate</b>; income and expenses at <b>transaction-date or average rates</b>; equity at historical rates. The balancing difference goes to <b>OCI</b> (foreign currency translation reserve) and is recycled to profit when the subsidiary is sold.' },
      { t: 'odoo', title: 'Multi-company & multi-currency in Odoo', html: '<ul><li><b>Multi-currency</b>: activate currencies, enable automatic rate updates; invoices in foreign currency post at the day’s rate; on payment, Odoo posts the <b>exchange difference</b> automatically to the Exchange Difference journal (gain/loss accounts set in Settings). Unrealised gains/losses can be booked via the <b>Unrealized Currency Gains/Losses</b> report adjustment.</li><li><b>Multi-company</b>: separate companies in one database with shared or separate charts; <b>inter-company rules</b> can mirror a sale in one company as a purchase in the other. Consolidation tooling depends on version (dedicated app in some versions; otherwise reports per company + eliminations).</li></ul>' },
      { t: 'bullets', items: ['Subsidiary (control) → full consolidation; associate/JV → equity method.', 'Goodwill = consideration + NCI − FV of net assets.', 'Eliminate intra-group balances, transactions and unrealised profit.', 'Monetary items retranslated at closing rate; non-monetary stay at historical rate.', 'Translation differences of foreign operations go to OCI.'] },
    ],
    quiz: [
      { q: 'A holding giving significant influence (but not control) is usually accounted for using…', o: ['Full consolidation', 'The equity method', 'Fair value through P&L only', 'Proportionate consolidation'], a: 1, e: 'Associates use the equity method.' },
      { q: 'Consideration 600k, NCI 150k, FV of net assets 700k. Goodwill?', o: ['50k', '100k', '−50k', '150k'], a: 0, e: '600 + 150 − 700 = 50k.' },
      { q: 'A subsidiary owned 75% is consolidated by including ___ of its assets.', o: ['75%', '100%', '25%', '0%'], a: 1, e: 'All assets and liabilities; NCI shows the outside share.' },
      { q: 'Which item is retranslated at the closing rate?', o: ['Inventory at cost', 'Equipment', 'Foreign-currency receivable', 'Prepaid rent'], a: 2, e: 'Monetary items are retranslated.' },
      { q: 'Invoice €1,000 at 1.10; paid at 1.15 ($ per €). The seller records…', o: ['$50 loss', '$50 gain', 'No difference', '$100 gain'], a: 1, e: 'Received $1,150 vs $1,100 booked.' },
      { q: 'Translation differences on consolidating a foreign subsidiary go to…', o: ['Revenue', 'OCI / translation reserve', 'Cost of sales', 'Goodwill'], a: 1, e: 'IAS 21: recognised in OCI.' },
    ],
    cards: [
      ['Control (IFRS 10)', 'Power over the investee, exposure to variable returns and ability to use power to affect returns.'],
      ['Goodwill', 'Consideration + NCI − fair value of identifiable net assets.'],
      ['Non-controlling interest', 'Equity in a subsidiary not attributable to the parent.'],
      ['Equity method', 'Investment at cost adjusted for share of profits and dividends.'],
      ['Functional currency', 'Currency of the primary economic environment of an entity.'],
      ['Monetary item', 'Units of currency held or to be received/paid (cash, receivables, payables, loans).'],
    ],
  });

  /* =============================== CH 25 =============================== */
  HF.addChapter({
    id: 'standards-audit-ethics',
    part: 'p4',
    title: 'Standards, Audit, Controls & Ethics',
    subtitle: 'The rules, the referees, and the conscience of accounting',
    art: 'gavel',
    level: 'Advanced',
    minutes: 30,
    quote: 'It takes 20 years to build a reputation and five minutes to ruin it. — Warren Buffett',
    goals: ['Know who sets accounting standards and the conceptual framework', 'Compare IFRS and US GAAP on key points', 'Describe the audit process and types of opinion', 'Apply internal control frameworks and the fraud triangle', 'Recall the fundamental ethical principles'],
    blocks: [
      { t: 'h', text: 'Who writes the rules?' },
      { t: 'cards', cols: 3, items: [{ icon: '🌍', t: 'IASB → IFRS', d: 'International Accounting Standards Board. IFRS is required or permitted in 140+ jurisdictions (EU, UK, Australia, much of Asia, Africa, Middle East, Latin America).' }, { icon: '🇺🇸', t: 'FASB → US GAAP', d: 'Financial Accounting Standards Board; codified in the Accounting Standards Codification (ASC). Required for US public companies.' }, { icon: '🏳️', t: 'National standards', d: 'Many countries adopt IFRS with local versions (e.g., Ind AS in India) or keep local GAAP for smaller entities. IFRS for SMEs exists for small companies.' }] },
      { t: 'h3', text: 'The conceptual framework' },
      { t: 'compare', cols: [{ t: 'Fundamental qualities', color: 'blue', items: ['<b>Relevance</b>: capable of making a difference to decisions (predictive/confirmatory value, materiality)', '<b>Faithful representation</b>: complete, neutral, free from error'] }, { t: 'Enhancing qualities', color: 'green', items: ['<b>Comparability</b>', '<b>Verifiability</b>', '<b>Timeliness</b>', '<b>Understandability</b>'] }] },
      { t: 'p', html: 'Constraint: <b>cost</b> — the benefits of reporting information should justify the cost of producing it.' },

      { t: 'h', text: 'IFRS vs US GAAP: the headlines' },
      {
        t: 'table',
        head: ['Topic', 'IFRS', 'US GAAP'],
        rows: [
          ['Approach', 'More principles-based', 'More rules-based, detailed industry guidance'],
          ['Inventory', 'LIFO prohibited; write-down reversals allowed', 'LIFO allowed; no reversals'],
          ['PPE measurement', 'Cost or revaluation model', 'Cost only'],
          ['Development costs', 'Capitalised if criteria met', 'Generally expensed (software has specific rules)'],
          ['Impairment reversal', 'Allowed (except goodwill)', 'Not allowed for assets held and used'],
          ['Leases (lessee)', 'Single model (IFRS 16)', 'Finance vs operating (ASC 842)'],
          ['Extraordinary items', 'Prohibited', 'Eliminated (since 2015)'],
          ['Interest paid in cash flows', 'Choice (IFRS 18 narrows from 2027)', 'Operating'],
          ['Revenue', 'IFRS 15', 'ASC 606 (largely converged)'],
        ],
      },

      { t: 'h', text: 'The audit' },
      { t: 'p', html: 'An external audit provides <b>reasonable (not absolute) assurance</b> that financial statements are free from material misstatement, whether due to fraud or error.' },
      { t: 'steps', items: [{ t: 'Acceptance & planning', d: 'Independence checks, understand the business, set materiality, assess risks.' }, { t: 'Controls testing', d: 'If relying on controls, test that they’re designed well and operate effectively.' }, { t: 'Substantive procedures', d: 'Analytical review, confirmations (banks, customers), inventory count attendance, vouching, recalculation, cut-off tests.' }, { t: 'Completion', d: 'Subsequent events, going concern, management representations, evaluate misstatements.' }, { t: 'Report', d: 'Issue the auditor’s opinion.' }] },
      {
        t: 'widget',
        name: 'match',
        opts: {
          id: 'ch25-opinions',
          title: 'Match the audit opinion',
          pairs: [
            ['Unmodified (“clean”)', 'Statements are fairly presented in all material respects.'],
            ['Qualified', 'Fair <b>except for</b> a material but not pervasive issue.'],
            ['Adverse', 'Material and pervasive misstatement — statements are not fairly presented.'],
            ['Disclaimer', 'Auditor couldn’t obtain enough evidence; material and pervasive — no opinion.'],
            ['Emphasis of matter', 'Opinion is clean but draws attention to an important disclosed issue.'],
          ],
        },
      },
      { t: 'p', html: 'Assertions auditors test: <b>existence/occurrence, completeness, accuracy, valuation, cut-off, rights & obligations, classification, presentation</b>.' },

      { t: 'h', text: 'Internal controls & fraud' },
      { t: 'cards', cols: 5, items: [{ icon: '🏛️', t: 'Control environment', d: 'Tone at the top, ethics, structure.' }, { icon: '⚠️', t: 'Risk assessment', d: 'What could go wrong?' }, { icon: '🔒', t: 'Control activities', d: 'Approvals, segregation, reconciliations, access controls.' }, { icon: '📣', t: 'Information & communication', d: 'Right info to the right people.' }, { icon: '👁️', t: 'Monitoring', d: 'Internal audit, reviews, follow-up.' }] },
      { t: 'p', html: 'Those are the five components of the <b>COSO</b> framework. In the US, <b>SOX</b> (Sarbanes-Oxley) requires public-company management to assess and report on internal control over financial reporting.' },
      { t: 'h3', text: 'The fraud triangle' },
      { t: 'flow', items: [{ t: '😰 Pressure<br><small>debts, targets</small>', c: '#f7c6d0' }, { t: '🚪 Opportunity<br><small>weak controls</small>', c: '#fff3a8' }, { t: '🤷 Rationalisation<br><small>“I’ll pay it back”</small>', c: '#bfe0f2' }] },
      { t: 'p', html: 'Controls attack <b>opportunity</b> — the one side management can directly control. Common schemes: fictitious vendors, skimming cash, expense reimbursement padding, revenue recognised early, hidden liabilities.' },
      { t: 'say', who: 'audrey', html: 'My favourite red flags: a vendor with the same bank account as an employee, invoices just below approval limits, round-number journal entries posted at midnight by a senior manager, and someone who never takes a holiday.' },

      { t: 'h', text: 'Ethics' },
      { t: 'p', html: 'Professional accountants (IFAC/IESBA Code, followed by ACCA, CIMA, ICAEW, ICAI, CPA bodies and others) commit to five fundamental principles:' },
      { t: 'cards', cols: 5, items: [{ icon: '🧭', t: 'Integrity', d: 'Straightforward and honest.' }, { icon: '⚖️', t: 'Objectivity', d: 'No bias, conflicts or undue influence.' }, { icon: '🎓', t: 'Competence & due care', d: 'Keep skills current; work diligently.' }, { icon: '🤐', t: 'Confidentiality', d: 'Don’t disclose or misuse information.' }, { icon: '🎩', t: 'Professional behaviour', d: 'Comply with laws; avoid discrediting the profession.' }] },
      { t: 'brain', html: 'Your manager asks you to “hold” a big supplier invoice until next month so this quarter hits its bonus target. Which principles are at stake? What would you do, and who could you talk to?' },
      { t: 'odoo', title: 'Controls in Odoo', html: 'Useful built-in controls: <b>user access rights</b> (Billing vs Accountant vs Adviser roles), <b>approval workflows</b> on purchases/bills (e.g., purchase approval thresholds), <b>lock dates</b>, the <b>audit trail</b> (logs changes on posted entries; can be enforced in several localizations), <b>hash/inalterability</b> checks for posted entries in some countries, and the chatter log on every document.' },
      { t: 'bullets', items: ['IASB issues IFRS; FASB issues US GAAP.', 'Framework: relevance & faithful representation, enhanced by comparability, verifiability, timeliness, understandability.', 'Audit gives reasonable assurance; opinions: unmodified, qualified, adverse, disclaimer.', 'COSO: environment, risk assessment, control activities, information & communication, monitoring.', 'Fraud triangle: pressure, opportunity, rationalisation.', 'Ethics: integrity, objectivity, competence & due care, confidentiality, professional behaviour.'] },
    ],
    quiz: [
      { q: 'Which body issues IFRS?', o: ['FASB', 'IASB', 'SEC', 'IRS'], a: 1, e: 'The International Accounting Standards Board.' },
      { q: 'Which is a fundamental qualitative characteristic?', o: ['Timeliness', 'Comparability', 'Faithful representation', 'Verifiability'], a: 2, e: 'Relevance and faithful representation are fundamental; others enhance.' },
      { q: 'An auditor finds a material, pervasive misstatement. The opinion is…', o: ['Unmodified', 'Qualified', 'Adverse', 'Emphasis of matter'], a: 2, e: 'Material and pervasive misstatement → adverse.' },
      { q: 'Which side of the fraud triangle do internal controls mainly reduce?', o: ['Pressure', 'Opportunity', 'Rationalisation', 'All equally'], a: 1, e: 'Controls remove opportunities.' },
      { q: 'Which is allowed under IFRS but not US GAAP?', o: ['LIFO', 'Revaluation of PPE', 'Expensing research', 'FIFO'], a: 1, e: 'IAS 16 revaluation model.' },
      { q: 'Keeping client information private is the principle of…', o: ['Objectivity', 'Confidentiality', 'Integrity', 'Competence'], a: 1, e: 'Confidentiality.' },
    ],
    cards: [
      ['IFRS', 'International Financial Reporting Standards, issued by the IASB.'],
      ['US GAAP', 'Generally accepted accounting principles in the US; codified by FASB (ASC).'],
      ['Reasonable assurance', 'High, but not absolute, level of assurance given by an audit.'],
      ['Qualified opinion', '“Except for” a material but not pervasive issue.'],
      ['COSO components', 'Control environment, risk assessment, control activities, information & communication, monitoring.'],
      ['Fraud triangle', 'Pressure, opportunity, rationalisation.'],
      ['Five ethical principles', 'Integrity, objectivity, professional competence & due care, confidentiality, professional behaviour.'],
    ],
  });
})();
