/* PART 1 — Foundations */
(function () {
  const HF = window.HF;
  HF.addPart({ id: 'p1', n: 1, title: 'Foundations', color: '#e4572e', badge: 'part1', desc: 'The equation, debits & credits, journals, ledgers, the trial balance and the accounting cycle.' });

  /* =============================== CH 1 =============================== */
  HF.addChapter({
    id: 'what-is-accounting',
    part: 'p1',
    title: 'Welcome to Accounting',
    subtitle: 'The language of business (and why your shoebox of receipts isn’t enough)',
    art: 'shop',
    level: 'Beginner',
    minutes: 15,
    quote: '“Accounting is the language of business.” — Warren Buffett. You wouldn’t move to a new country without learning to speak. Same with business.',
    goals: ['Explain what accounting is and who relies on it', 'Name the five elements: assets, liabilities, equity, revenue and expenses', 'Tell bookkeeping from accounting', 'List the main branches of accounting and the core assumptions behind it'],
    blocks: [
      { t: 'h', text: 'Meet Max (and his shoebox)' },
      {
        t: 'story',
        panels: [
          { who: 'max', text: 'I opened <b>Max’s Bikes</b> six months ago. Sales feel great! I keep every receipt in this shoebox.' },
          { art: 'coins', text: 'There’s $4,200 in the bank. Last month there was $6,000. Am I losing money?' },
          { who: 'penny', text: 'Not necessarily! You bought <b>$5,000 of bikes</b> that are still on your shelves. That’s not lost money — it’s an <b>asset</b>.' },
          { who: 'max', think: true, text: '…an asset? I think I need to learn this language.' },
        ],
      },
      { t: 'p', html: 'Max’s problem is everybody’s problem. A bank balance tells you <i>how much cash you have</i>. It does <b>not</b> tell you whether you’re profitable, how much you owe, what customers owe <i>you</i>, or whether you can afford a new shop assistant. <b>Accounting</b> answers those questions.' },
      { t: 'formula', html: 'Accounting = Identify → Record → Summarise → Communicate', note: '…financial events, so people can make better decisions.' },
      {
        t: 'steps',
        items: [
          { t: 'Identify', d: 'Spot the events that matter financially: a sale, a purchase, paying rent, taking a loan. (A customer smiling at a bike? Not a transaction.)' },
          { t: 'Record', d: 'Write each event down in a systematic way — the <b>journal</b> — with dates, amounts and which accounts are affected.' },
          { t: 'Summarise', d: 'Group thousands of records into accounts (the <b>ledger</b>) and then into a few powerful reports: the <b>financial statements</b>.' },
          { t: 'Communicate', d: 'Hand those reports to people who make decisions: owners, managers, banks, investors, tax authorities.' },
        ],
      },
      { t: 'brain', html: 'Max has $4,200 in the bank. Name <b>three</b> things that bank balance can’t tell him about his business. (Think about the shelves, the customers, and the bank loan…)' },

      { t: 'h', text: 'Who reads the numbers?' },
      { t: 'p', html: 'Accounting is a <b>service</b>. It exists because different people need to trust and use the same information. Each has a different question in mind:' },
      {
        t: 'cards',
        cols: 4,
        items: [
          { icon: '🧑‍💼', t: 'Owners', d: 'Am I making money? Should I open a second shop?', color: 'red' },
          { icon: '📋', t: 'Managers', d: 'Which product line is most profitable? Are costs under control?', color: 'yellow' },
          { icon: '🏦', t: 'Lenders', d: 'Can this business repay a loan, with interest?', color: 'blue' },
          { icon: '📈', t: 'Investors', d: 'Is this a good company to buy shares in?', color: 'green' },
          { icon: '🏛️', t: 'Tax authorities', d: 'How much income tax and VAT/GST is due?', color: 'purple' },
          { icon: '👷', t: 'Employees', d: 'Is my job safe? Can the company afford a raise?', color: 'blue' },
          { icon: '🤝', t: 'Suppliers', d: 'Will they pay my invoice on time if I give credit?', color: 'yellow' },
          { icon: '🧾', t: 'Regulators', d: 'Are rules and reporting standards being followed?', color: 'red' },
        ],
      },
      { t: 'sticky', html: '<b>Internal users</b> (owners, managers) get detailed, frequent reports → <i>management accounting</i>.<br><b>External users</b> (banks, investors, tax office) get standardised reports → <i>financial accounting</i>.' },

      { t: 'h', text: 'Bookkeeping vs accounting' },
      {
        t: 'compare',
        cols: [
          { t: '📒 Bookkeeping', color: 'yellow', items: ['Records daily transactions', 'Follows rules & routines', 'Issues invoices, records bills, matches bank lines', 'Answers “what happened?”', 'Foundation of everything else'] },
          { t: '🧮 Accounting', color: 'blue', items: ['Designs the system & policies', 'Makes adjustments and estimates', 'Prepares and analyses financial statements', 'Answers “what does it mean & what should we do?”', 'Tax planning, budgeting, advising'] },
        ],
      },
      { t: 'say', who: 'penny', html: 'Bookkeeping is the <b>recording</b>. Accounting is the <b>thinking</b>. Today, software like Odoo does a lot of the recording for you — which means the thinking is where you add value!' },

      { t: 'h', text: 'The five elements' },
      { t: 'p', html: 'Every number in accounting belongs to one of just <b>five</b> buckets. Learn these and you can read any financial statement on Earth.' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '💰', t: 'Assets', d: 'Resources the business <b>controls</b> that will bring future benefit. Cash, inventory, equipment, buildings, amounts customers owe you (receivables).', color: 'blue' },
          { icon: '📜', t: 'Liabilities', d: 'What the business <b>owes</b> to outsiders. Loans, unpaid supplier bills (payables), taxes due, wages owed.', color: 'red' },
          { icon: '🧑', t: 'Equity', d: 'The <b>owner’s claim</b>: what’s left for owners after paying all liabilities. Capital invested + profits kept.', color: 'green' },
          { icon: '📈', t: 'Revenue (Income)', d: 'Increases in equity from doing business: sales of bikes, repair fees, interest earned.', color: 'yellow' },
          { icon: '📉', t: 'Expenses', d: 'Decreases in equity from running the business: rent, wages, electricity, cost of bikes sold.', color: 'purple' },
        ],
      },
      { t: 'formula', html: 'Profit = Revenue − Expenses', note: 'Profit belongs to the owner, so it increases equity.' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch1-elements',
          title: 'Which bucket?',
          sub: 'Classify each item from Max’s Bikes into one of the five elements.',
          bins: [
            { id: 'A', label: 'Asset', color: '#2e86ab' },
            { id: 'L', label: 'Liability', color: '#e4572e' },
            { id: 'E', label: 'Equity', color: '#3a9d5d' },
            { id: 'R', label: 'Revenue', color: '#c08a00' },
            { id: 'X', label: 'Expense', color: '#8e5ea2' },
          ],
          items: [
            { text: 'Cash in the bank', bin: 'A', why: 'Cash is the most obvious asset.' },
            { text: 'Bikes on the shelf', bin: 'A', why: 'Inventory is an asset — it will be sold for cash later.' },
            { text: 'Bank loan', bin: 'L', why: 'A loan must be repaid — a liability.' },
            { text: 'Unpaid supplier bill', bin: 'L', why: 'Accounts payable: money owed to suppliers.' },
            { text: 'Money Max invested to start', bin: 'E', why: 'Owner’s capital is equity.' },
            { text: 'Bike sales', bin: 'R', why: 'Sales are revenue.' },
            { text: 'Repair service fees', bin: 'R', why: 'Fees earned from services are revenue.' },
            { text: 'Shop rent', bin: 'X', why: 'Rent is a cost of running the business.' },
            { text: 'Staff wages', bin: 'X', why: 'Wages are an expense.' },
            { text: 'Amount a customer owes Max', bin: 'A', why: 'Accounts receivable — a right to receive cash. Asset!' },
            { text: 'Delivery van', bin: 'A', why: 'Equipment/vehicles are (non-current) assets.' },
            { text: 'Electricity bill', bin: 'X', why: 'Utilities are expenses.' },
          ],
        },
      },
      { t: 'watch', html: 'Buying a <b>van</b> is not an expense — it’s an asset, because it helps the business for years. Its cost becomes an expense <i>slowly</i>, through <b>depreciation</b> (Chapter 16). Mixing up assets and expenses is one of the most common beginner mistakes.' },

      { t: 'h', text: 'The family tree of accounting' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '📊', t: 'Financial accounting', d: 'Prepares general-purpose financial statements for outsiders, following standards like IFRS or US GAAP.' },
          { icon: '🧭', t: 'Management accounting', d: 'Budgets, forecasts, performance reports and decision analysis for insiders. No fixed format.' },
          { icon: '🏭', t: 'Cost accounting', d: 'Works out what it costs to make a product or deliver a service.' },
          { icon: '🧾', t: 'Tax accounting', d: 'Calculates and files income tax, VAT/GST, withholding taxes; plans legally to minimise them.' },
          { icon: '🔍', t: 'Auditing', d: 'Independent check that financial statements are fairly presented. External and internal audit.' },
          { icon: '🕵️', t: 'Forensic accounting', d: 'Investigates fraud and disputes. Accounting meets detective work.' },
          { icon: '🏛️', t: 'Public sector & non-profit', d: 'Governments and charities: fund accounting, budgets vs actuals, accountability.' },
          { icon: '💻', t: 'Accounting systems', d: 'Designing ERP/accounting software setups — like Odoo — and the controls inside them.' },
          { icon: '🌱', t: 'Sustainability reporting', d: 'Measuring and reporting environmental & social impacts (e.g., ISSB/IFRS S1–S2, ESRS).' },
        ],
      },

      { t: 'h', text: 'The rules of the game: core assumptions' },
      { t: 'p', html: 'Accountants everywhere agree on some basic assumptions and principles. They’re why two accountants looking at the same shoebox should produce similar books.' },
      {
        t: 'table',
        head: ['Concept', 'In plain English', 'Max example'],
        rows: [
          ['<b>Business entity</b>', 'The business is separate from its owner.', 'Max’s personal groceries don’t go in the shop’s books.'],
          ['<b>Going concern</b>', 'Assume the business will keep running.', 'The van is valued at cost less depreciation, not fire-sale price.'],
          ['<b>Monetary unit</b>', 'Record only things measurable in money.', 'Staff morale isn’t on the balance sheet.'],
          ['<b>Periodicity</b>', 'Chop life into periods (month, quarter, year).', 'Max reports profit for January, for Q1, for the year.'],
          ['<b>Historical cost</b>', 'Record assets at what you paid (with exceptions).', 'Bikes bought for $300 are recorded at $300.'],
          ['<b>Accrual basis</b>', 'Record income when earned and expenses when incurred — not when cash moves.', 'A repair done on credit is revenue today.'],
          ['<b>Matching</b>', 'Put expenses in the same period as the revenue they help earn.', 'The cost of a bike is an expense when the bike is sold.'],
          ['<b>Consistency</b>', 'Use the same methods period after period.', 'Don’t switch depreciation methods every year.'],
          ['<b>Prudence</b>', 'Don’t overstate assets or income; don’t hide losses.', 'Expect some customers won’t pay → allowance for bad debts.'],
          ['<b>Materiality</b>', 'Small amounts that don’t change decisions can be simplified.', 'A $5 stapler is expensed, not depreciated over 5 years.'],
          ['<b>Full disclosure</b>', 'Tell users everything that matters, in notes if needed.', 'A pending lawsuit gets a note.'],
        ],
      },
      {
        t: 'nodumb',
        qa: [
          ['Is accounting just maths?', 'Surprisingly little maths: mostly adding and subtracting. It’s much more about <b>classification</b> (which bucket?) and <b>judgement</b> (when is revenue earned? will this customer pay?).'],
          ['Do I need to memorise IFRS or GAAP?', 'No. Learn the logic first — the equation, debits and credits, accruals. The standards are detailed rulebooks built on top of that logic. Chapter 25 gives you the map.'],
          ['Why can’t I just use the bank statement?', 'Because the bank only shows cash. It ignores what customers owe you, what you owe suppliers, inventory, equipment — and timing. Profit and cash are different things!'],
          ['What’s the difference between “income” and “revenue”?', 'Often used interchangeably. Strictly, <b>revenue</b> is from ordinary activities (sales), while <b>income</b> also includes gains (like selling an old van for more than its book value). In Odoo, both appear as “Income” and “Other Income” account types.'],
        ],
      },
      {
        t: 'pencil',
        html: 'For each event, decide: is it an accounting <b>transaction</b> for Max’s Bikes?',
        items: [
          { q: 'Max signs a contract to hire a mechanic starting next month.', a: 'Not yet a transaction — nothing has been exchanged. It becomes one when the mechanic works (wages expense) or is paid.' },
          { q: 'Max buys a $50 tyre pump with the shop’s debit card.', a: 'Yes — cash goes down, and an expense (or small asset) goes up.' },
          { q: 'Max buys a sofa for his own home using his personal card.', a: 'No — business entity concept! It’s personal, not the shop’s.' },
          { q: 'A customer orders a bike for delivery and payment next week.', a: 'Not yet revenue — the bike hasn’t been delivered. (In Odoo this is a <i>sales order</i>, which doesn’t touch the books until it’s invoiced/delivered.)' },
        ],
      },
      {
        t: 'bullets',
        items: [
          'Accounting identifies, records, summarises and communicates financial information.',
          'Users are internal (owners, managers) and external (lenders, investors, tax authorities).',
          'Bookkeeping records; accounting interprets and advises.',
          'Everything fits into five elements: <b>assets, liabilities, equity, revenue, expenses</b>.',
          'Buying long-lived things creates assets, not expenses.',
          'Key assumptions: entity, going concern, monetary unit, periodicity, accrual, matching, consistency, prudence, materiality.',
        ],
      },
    ],
    quiz: [
      { q: 'Which of these is an <b>asset</b>?', o: ['Bank loan', 'Delivery van owned by the business', 'Rent expense', 'Owner’s capital'], a: 1, e: 'The van is a resource controlled by the business that brings future benefit.' },
      { q: 'Max pays for his family holiday from his personal account. In the shop’s books this is…', o: ['An expense', 'An asset', 'Not recorded at all', 'A liability'], a: 2, e: 'Business entity concept: personal transactions stay out of the business books.' },
      { q: 'Which users mainly rely on <b>management accounting</b>?', o: ['Tax authorities', 'Bank lenders', 'Internal managers', 'Shareholders of other companies'], a: 2, e: 'Management accounting serves internal decision-makers with detailed, custom reports.' },
      { q: 'Profit equals…', o: ['Assets − Liabilities', 'Revenue − Expenses', 'Cash in − Cash out', 'Equity + Liabilities'], a: 1, e: 'Profit (net income) = revenue − expenses. Note it is NOT the same as cash in − cash out.' },
      { q: 'The principle of recording income when earned rather than when cash is received is called…', o: ['Going concern', 'Historical cost', 'Accrual basis', 'Materiality'], a: 2, e: 'Under the accrual basis, timing follows the economic event, not the cash.' },
      { q: 'An unpaid bill from a supplier is a…', o: ['Liability', 'Expense only', 'Asset', 'Revenue'], a: 0, e: 'Money owed to a supplier is a liability (accounts payable).' },
      { q: 'Why is a $5 stapler expensed immediately even though it will last years?', o: ['Prudence', 'Materiality', 'Going concern', 'Monetary unit'], a: 1, e: 'It’s immaterial — tracking it as an asset wouldn’t change anyone’s decisions.' },
      { q: 'Which branch provides an independent opinion on financial statements?', o: ['Tax accounting', 'Cost accounting', 'Auditing', 'Bookkeeping'], a: 2, e: 'Auditors examine and express an opinion on whether statements are fairly presented.' },
    ],
    cards: [
      ['Accounting', 'Identifying, recording, summarising and communicating financial information for decision-making.'],
      ['Asset', 'A resource controlled by the business from past events, expected to bring future economic benefits.'],
      ['Liability', 'A present obligation to transfer economic resources (e.g., pay cash) arising from past events.'],
      ['Equity', 'The owner’s residual interest: Assets − Liabilities.'],
      ['Revenue', 'Income from ordinary activities, such as sales of goods or services.'],
      ['Expense', 'A decrease in economic benefits during the period (e.g., rent, wages) that reduces equity.'],
      ['Business entity concept', 'The business’s records are kept separate from the owner’s personal affairs.'],
      ['Going concern', 'Assumption that the business will continue operating for the foreseeable future.'],
      ['Matching principle', 'Expenses are recognised in the same period as the revenues they help generate.'],
    ],
  });

  /* =============================== CH 2 =============================== */
  HF.addChapter({
    id: 'accounting-equation',
    part: 'p1',
    title: 'The Accounting Equation',
    subtitle: 'One equation to rule them all — and it never, ever breaks',
    art: 'scale',
    level: 'Beginner',
    minutes: 20,
    quote: 'Everything a business owns was paid for by someone: either a lender or an owner. That’s the whole secret.',
    goals: ['State the accounting equation and its expanded form', 'Analyse how any transaction affects assets, liabilities and equity', 'Prove that every transaction keeps the equation in balance'],
    blocks: [
      { t: 'h', text: 'Where did the stuff come from?' },
      { t: 'p', html: 'Look around Max’s shop: bikes, a till, a van, cash in the bank. Now ask a simple question: <b>who paid for all of this?</b> There are only two possible answers:' },
      {
        t: 'compare',
        cols: [
          { t: 'Outsiders (creditors)', color: 'red', items: ['The bank lent money for the van', 'A supplier delivered bikes but hasn’t been paid yet', 'These claims are <b>liabilities</b>'] },
          { t: 'The owner', color: 'green', items: ['Max put in his savings', 'Profits Max left in the business', 'These claims are <b>equity</b>'] },
        ],
      },
      { t: 'formula', html: 'Assets = Liabilities + Equity', note: 'What we own = what we owe + what’s left for the owner' },
      { t: 'art', name: 'scale', caption: 'Think of a balance scale. Assets on the left pan; the claims on those assets on the right. It must always be level.', notes: [{ x: 2, y: 4, t: 'what we HAVE' }, { x: 70, y: 4, t: 'who FUNDED it' }] },
      { t: 'say', who: 'sam', html: 'Wait… if the business owns $100,000 of stuff and owes the bank $60,000, then Max’s share is $40,000?' },
      { t: 'say', who: 'penny', right: true, html: 'Exactly! Equity is a <b>residual</b> — whatever’s left after creditors. That’s why you’ll also see it written as <b>Equity = Assets − Liabilities</b> (a.k.a. <i>net assets</i> or <i>net worth</i>).' },

      { t: 'h', text: 'Opening up equity' },
      { t: 'p', html: 'Equity changes for four reasons. Owners put money in (capital), take money out (drawings or dividends), and the business earns revenue and incurs expenses. So we can expand the equation:' },
      { t: 'formula', html: 'A = L + Capital − Drawings + Revenue − Expenses', note: 'This expanded form is the secret behind debits & credits (next chapter).' },
      {
        t: 'cards',
        cols: 4,
        items: [
          { icon: '⬆️', t: 'Capital', d: 'Owner invests → equity up.', color: 'green' },
          { icon: '⬇️', t: 'Drawings / dividends', d: 'Owner takes out → equity down.', color: 'red' },
          { icon: '⬆️', t: 'Revenue', d: 'Earning income → equity up.', color: 'yellow' },
          { icon: '⬇️', t: 'Expenses', d: 'Using up resources → equity down.', color: 'purple' },
        ],
      },
      { t: 'watch', html: 'Drawings are <b>not</b> an expense. Max taking $500 home reduces equity, but it isn’t a cost of running the shop, so it does not reduce profit. In a company, the equivalent is <b>dividends</b>.' },

      { t: 'h', text: 'Watch the scale in action' },
      { t: 'p', html: 'Here are Max’s first transactions. Click them in order. Notice how the scale tips for a moment… then the <b>second effect</b> brings it back. That’s <b>duality</b>: every transaction has (at least) two effects.' },
      {
        t: 'widget',
        name: 'equation',
        opts: {
          id: 'ch2-eq',
          transactions: [
            { text: 'Max invests $20,000 of savings into the business bank account', effects: [{ k: 'a', acct: 'Cash', v: 20000 }, { k: 'e', acct: 'Capital', v: 20000 }], note: 'Assets up, equity up.' },
            { text: 'Borrows $10,000 from the bank', effects: [{ k: 'a', acct: 'Cash', v: 10000 }, { k: 'l', acct: 'Bank loan', v: 10000 }], note: 'Assets up, liabilities up.' },
            { text: 'Buys a van for $12,000 cash', effects: [{ k: 'a', acct: 'Van', v: 12000 }, { k: 'a', acct: 'Cash', v: -12000 }], note: 'One asset up, another down. Totals unchanged!' },
            { text: 'Buys bikes for $8,000 on credit', effects: [{ k: 'a', acct: 'Inventory', v: 8000 }, { k: 'l', acct: 'Payables', v: 8000 }], note: 'Assets up, liabilities up.' },
            { text: 'Sells bikes costing $3,000 for $5,000 cash', effects: [{ k: 'a', acct: 'Cash', v: 5000 }, { k: 'e', acct: 'Revenue', v: 5000 }, { k: 'a', acct: 'Inventory', v: -3000 }, { k: 'e', acct: 'Cost of sales', v: -3000 }], note: 'Revenue raises equity; the cost of bikes sold lowers it. Net profit $2,000.' },
            { text: 'Pays $1,500 rent', effects: [{ k: 'a', acct: 'Cash', v: -1500 }, { k: 'e', acct: 'Rent expense', v: -1500 }], note: 'Expenses reduce equity.' },
            { text: 'Pays the supplier $4,000', effects: [{ k: 'a', acct: 'Cash', v: -4000 }, { k: 'l', acct: 'Payables', v: -4000 }], note: 'Assets down, liabilities down. Equity untouched.' },
            { text: 'Max withdraws $1,000 for personal use', effects: [{ k: 'a', acct: 'Cash', v: -1000 }, { k: 'e', acct: 'Drawings', v: -1000 }], note: 'Equity down — but it’s not an expense.' },
          ],
        },
      },
      { t: 'brain', html: 'In transaction 3 (buying the van for cash), the scale didn’t move at all. Can you think of another transaction that changes the <i>contents</i> of the books without changing the <i>totals</i>? <i>(Hint: a customer pays what they owe.)</i>' },

      { t: 'h', text: 'The nine possible moves' },
      { t: 'p', html: 'Every transaction is one of a handful of patterns. Here is a cheat sheet:' },
      {
        t: 'table',
        head: ['Pattern', 'Example', 'A', 'L', 'E'],
        rows: [
          ['Asset ↑, Liability ↑', 'Borrow from the bank', '↑', '↑', ''],
          ['Asset ↑, Equity ↑', 'Owner invests; earn cash revenue', '↑', '', '↑'],
          ['Asset ↑, Asset ↓', 'Buy equipment for cash; collect receivable', '↑↓', '', ''],
          ['Asset ↓, Liability ↓', 'Repay a loan; pay a supplier', '↓', '↓', ''],
          ['Asset ↓, Equity ↓', 'Pay an expense; owner withdraws', '↓', '', '↓'],
          ['Liability ↑, Equity ↓', 'Receive a utility bill (unpaid)', '', '↑', '↓'],
          ['Liability ↓, Equity ↑', 'Creditor forgives a debt (gain)', '', '↓', '↑'],
          ['Liability ↑, Liability ↓', 'Replace a supplier debt with a bank loan', '', '↑↓', ''],
          ['Equity ↑, Equity ↓', 'Transfer profit to a reserve', '', '', '↑↓'],
        ],
      },
      {
        t: 'pencil',
        html: 'Fill in the missing number. (Use A = L + E.)',
        items: [
          { q: 'Assets $80,000; Liabilities $35,000; Equity = ?', input: true, a: '$45,000 (80,000 − 35,000).' },
          { q: 'Liabilities $12,000; Equity $30,000; Assets = ?', input: true, a: '$42,000.' },
          { q: 'At the start of the year, equity was $50,000. During the year: capital added $10,000, drawings $8,000, revenue $90,000, expenses $70,000. Closing equity?', input: true, a: '50,000 + 10,000 − 8,000 + 90,000 − 70,000 = <b>$72,000</b>.' },
          { q: 'Assets rose by $15,000 and liabilities fell by $5,000 during the year. What happened to equity?', input: true, a: 'Equity rose by <b>$20,000</b> (ΔA = ΔL + ΔE → 15,000 = −5,000 + ΔE).' },
        ],
      },
      {
        t: 'chat',
        title: 'Tonight’s talk: Liability and Equity — who has the better claim?',
        left: 'Liability',
        right: 'Equity',
        lines: [
          ['L', 'Let’s be clear: when things go wrong, <b>I</b> get paid first. Lenders and suppliers are legally owed their money.'],
          ['R', 'Sure, you get your fixed amount. But that’s it. If Max’s Bikes becomes the next big thing, all the upside is <b>mine</b>.'],
          ['L', 'And if it goes bust, you could get nothing. You’re the residual — the leftovers.'],
          ['R', 'Risk and reward, my friend. And without me, no bank would lend you a cent. I’m the cushion that makes you feel safe.'],
          ['L', '…fair. Same balance sheet, different seats on the plane.'],
        ],
      },
      {
        t: 'nodumb',
        qa: [
          ['Can equity be negative?', 'Yes! If liabilities exceed assets (e.g., after years of losses), equity is negative — sometimes called a “deficit”. It’s a warning sign that the business may not be a going concern.'],
          ['Does a profitable month always mean more cash?', 'No. If you sold on credit, profit goes up but cash doesn’t (receivables do). If you bought inventory for cash, cash went down but no expense happened yet. Profit ≠ cash!'],
          ['Is the equation the same in every country?', 'Yes. Standards differ in details, but the equation is universal — it’s just logic.'],
        ],
      },
      {
        t: 'bullets',
        items: [
          '<b>Assets = Liabilities + Equity</b>, always.',
          'Equity = Capital − Drawings + Revenue − Expenses (+ opening retained profits).',
          'Every transaction has at least two effects (duality), so the equation can’t break.',
          'Some transactions only swap one asset for another — totals unchanged.',
          'Drawings/dividends reduce equity but are <b>not</b> expenses.',
        ],
      },
    ],
    quiz: [
      { q: 'If assets are $150,000 and equity is $90,000, liabilities are…', o: ['$240,000', '$60,000', '$90,000', '$150,000'], a: 1, e: 'L = A − E = 150,000 − 90,000 = 60,000.' },
      { q: 'Buying equipment for cash causes…', o: ['Assets ↑, Equity ↑', 'Assets ↑, Liabilities ↑', 'One asset ↑, another asset ↓', 'Assets ↓, Equity ↓'], a: 2, e: 'Equipment up, cash down. Totals unchanged.' },
      { q: 'Paying a supplier you owe causes…', o: ['Assets ↓, Liabilities ↓', 'Assets ↓, Equity ↓', 'Liabilities ↑, Equity ↓', 'No change'], a: 0, e: 'Cash goes down and accounts payable goes down.' },
      { q: 'Which transaction <b>decreases</b> equity but is NOT an expense?', o: ['Paying wages', 'Owner drawings', 'Buying inventory', 'Repaying a loan'], a: 1, e: 'Drawings (or dividends) reduce equity but are distributions, not costs of earning revenue.' },
      { q: 'Receiving an electricity bill that will be paid next month causes…', o: ['Assets ↓, Equity ↓', 'Liabilities ↑, Equity ↓', 'Assets ↑, Liabilities ↑', 'Liabilities ↑, Assets ↓'], a: 1, e: 'An expense (equity ↓) and a payable (liability ↑).' },
      { q: 'Opening equity $40k, revenue $60k, expenses $45k, drawings $5k, no new capital. Closing equity?', o: ['$50k', '$55k', '$45k', '$60k'], a: 0, e: '40 + 60 − 45 − 5 = 50.' },
      { q: 'A customer pays $500 they owed. The effect is…', o: ['Revenue ↑', 'Cash ↑, Receivables ↓', 'Cash ↑, Equity ↑', 'Cash ↑, Liabilities ↑'], a: 1, e: 'The revenue was already recorded when the sale was made; now one asset (receivable) turns into another (cash).' },
    ],
    cards: [
      ['The accounting equation', 'Assets = Liabilities + Equity'],
      ['Expanded equation', 'A = L + Capital − Drawings + Revenue − Expenses'],
      ['Duality', 'Every transaction has at least two equal effects, so the equation always balances.'],
      ['Net assets', 'Assets − Liabilities = Equity'],
      ['Drawings', 'Amounts the owner takes out for personal use. Reduce equity; not an expense.'],
      ['Profit vs cash', 'Profit is revenue − expenses on an accrual basis; cash flow is actual money in/out. They often differ.'],
    ],
  });

  /* =============================== CH 3 =============================== */
  HF.addChapter({
    id: 'debits-credits',
    part: 'p1',
    title: 'Debits & Credits',
    subtitle: 'Left and right. That’s it. (Okay, a little more than that.)',
    art: 'tchart',
    level: 'Beginner',
    minutes: 25,
    quote: 'Debit doesn’t mean bad. Credit doesn’t mean good. They mean <b>left</b> and <b>right</b>.',
    goals: ['Explain what debit and credit really mean', 'Use DEALER to know which side increases each account type', 'Apply the traditional golden rules (personal, real, nominal)', 'State the normal balance of any account'],
    blocks: [
      { t: 'h', text: 'Forget everything your bank told you' },
      { t: 'p', html: 'You’ve heard “my account was credited” (good news!) and “debit card” (money leaves). So you might think <b>credit = good, debit = bad</b>. Throw that away. In accounting:' },
      { t: 'formula', html: 'Debit (Dr) = LEFT side &nbsp;·&nbsp; Credit (Cr) = RIGHT side', note: 'From Latin <i>debere</i> (to owe) and <i>credere</i> (to trust/believe). Today they’re just directions.' },
      { t: 'art', name: 'tchart', caption: 'A T-account: name on top, debits on the left, credits on the right.', notes: [{ x: 4, y: 40, t: 'left = debit' }, { x: 74, y: 40, t: 'right = credit' }] },
      { t: 'watch', html: 'Your <b>bank</b> keeps books from <i>its</i> point of view. Your deposit is money the bank owes you — a <b>liability</b> for the bank. So when your balance goes up, the bank <b>credits</b> your account. In <i>your</i> books, the same deposit is a <b>debit</b> to Cash. Same event, opposite perspectives!' },

      { t: 'h', text: 'Which side makes it go up?' },
      { t: 'p', html: 'Remember the equation <b>A = L + E</b>? Assets sit on the <b>left</b>, so they increase on the <b>left</b> (debit). Liabilities and equity sit on the <b>right</b>, so they increase on the <b>right</b> (credit). Revenue increases equity → credit. Expenses and drawings decrease equity → debit.' },
      { t: 'formula', html: '<span class="dr">D·E·A</span> &nbsp;|&nbsp; <span class="cr">L·E·R</span>', note: '<b>D</b>rawings/Dividends, <b>E</b>xpenses, <b>A</b>ssets increase with a DEBIT. <b>L</b>iabilities, <b>E</b>quity, <b>R</b>evenue increase with a CREDIT.' },
      {
        t: 'table',
        head: ['Account type', 'Increase', 'Decrease', 'Normal balance'],
        rows: [
          ['<b>Assets</b> (cash, inventory, receivables, equipment)', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>'],
          ['<b>Expenses</b> (rent, wages, COGS)', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>'],
          ['<b>Drawings / Dividends</b>', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>'],
          ['<b>Liabilities</b> (payables, loans, taxes due)', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>'],
          ['<b>Equity</b> (capital, retained earnings)', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>'],
          ['<b>Revenue / Income</b> (sales, fees, interest earned)', '<span class="cr">Credit</span>', '<span class="dr">Debit</span>', '<span class="cr">Credit</span>'],
        ],
      },
      { t: 'sticky', side: 'right', html: 'The golden law of double entry:<br><b>Total debits = Total credits</b><br>for every single transaction.' },
      { t: 'p', html: 'The <b>normal balance</b> is the side where an account’s increases go — and therefore where its balance usually sits. A Cash account with a credit balance means you’re overdrawn. A Revenue account with a debit balance? Something’s probably wrong.' },
      { t: 'say', who: 'sam', html: 'Why do expenses increase with a debit? They’re not assets!' },
      { t: 'say', who: 'penny', right: true, html: 'Because an expense <b>reduces equity</b>, and equity decreases on the debit side. Expenses are just “negative equity” kept in their own accounts so we can see them. Same for drawings.' },

      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch3-drcr',
          title: 'Debit or credit?',
          sub: 'Sort each change to the side that records it.',
          bins: [
            { id: 'D', label: 'DEBIT (left)', color: '#2e86ab' },
            { id: 'C', label: 'CREDIT (right)', color: '#e4572e' },
          ],
          items: [
            { text: 'Cash increases', bin: 'D', why: 'Asset ↑ = debit.' },
            { text: 'Cash decreases', bin: 'C', why: 'Asset ↓ = credit.' },
            { text: 'Bank loan increases', bin: 'C', why: 'Liability ↑ = credit.' },
            { text: 'Bank loan is repaid', bin: 'D', why: 'Liability ↓ = debit.' },
            { text: 'Sales revenue earned', bin: 'C', why: 'Revenue ↑ = credit.' },
            { text: 'Rent expense incurred', bin: 'D', why: 'Expense ↑ = debit.' },
            { text: 'Owner invests capital', bin: 'C', why: 'Equity ↑ = credit.' },
            { text: 'Owner withdraws cash (drawings ↑)', bin: 'D', why: 'Drawings ↑ = debit.' },
            { text: 'Inventory purchased', bin: 'D', why: 'Asset ↑ = debit.' },
            { text: 'Supplier is owed more (payables ↑)', bin: 'C', why: 'Liability ↑ = credit.' },
            { text: 'Customer owes us (receivables ↑)', bin: 'D', why: 'Asset ↑ = debit.' },
            { text: 'Sales returned by customer (revenue ↓)', bin: 'D', why: 'Revenue ↓ = debit (usually via a Sales Returns account).' },
          ],
        },
      },

      { t: 'h', text: 'The traditional golden rules' },
      { t: 'p', html: 'In many countries (India, Sri Lanka, Pakistan, Bangladesh and others) students learn three <b>golden rules</b> based on classifying accounts as Personal, Real or Nominal. They give the same answers as DEALER — just a different lens.' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '🧑', t: 'Personal accounts', d: 'People and organisations: customers, suppliers, banks, the owner’s capital.<br><b>Debit the receiver, credit the giver.</b>', color: 'blue' },
          { icon: '🧱', t: 'Real accounts', d: 'Things/property: cash, building, furniture, inventory, goodwill.<br><b>Debit what comes in, credit what goes out.</b>', color: 'green' },
          { icon: '🏷️', t: 'Nominal accounts', d: 'Incomes, expenses, gains and losses: rent, wages, sales, interest.<br><b>Debit all expenses and losses, credit all incomes and gains.</b>', color: 'yellow' },
        ],
      },
      { t: 'entry', title: 'Example: paid rent of 2,000 in cash', lines: [['Rent A/c — nominal, an expense → Dr', 2000, 0], ['Cash A/c — real, goes out → Cr', 0, 2000]], narr: 'Being rent paid for the month' },
      { t: 'entry', title: 'Example: bought goods on credit from Gear Supply Co. for 5,000', lines: [['Purchases A/c — nominal/expense → Dr', 5000, 0], ['Gear Supply Co. — personal, the giver → Cr', 0, 5000]], narr: 'Being goods purchased on credit' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch3-prn',
          title: 'Personal, Real or Nominal?',
          bins: [
            { id: 'P', label: 'Personal', color: '#2e86ab' },
            { id: 'R', label: 'Real', color: '#3a9d5d' },
            { id: 'N', label: 'Nominal', color: '#c08a00' },
          ],
          items: [
            { text: 'Customer: Azure Interior', bin: 'P', why: 'A person/organisation.' },
            { text: 'Bank of Springfield', bin: 'P', why: 'A bank is an organisation — personal account.' },
            { text: 'Capital (owner)', bin: 'P', why: 'Represents the owner — personal (representative) account.' },
            { text: 'Cash', bin: 'R', why: 'A tangible asset.' },
            { text: 'Furniture', bin: 'R', why: 'Property — real.' },
            { text: 'Goodwill', bin: 'R', why: 'An intangible real account.' },
            { text: 'Salaries', bin: 'N', why: 'An expense.' },
            { text: 'Commission received', bin: 'N', why: 'An income.' },
            { text: 'Outstanding salaries', bin: 'P', why: 'Owed to employees — a representative personal account.' },
            { text: 'Interest paid', bin: 'N', why: 'An expense.' },
          ],
        },
      },
      { t: 'relax', html: 'Use whichever method clicks for you. <b>DEALER</b> (modern/American approach) and the <b>golden rules</b> (traditional/British-Indian approach) always agree. Most software, including Odoo, simply shows you Debit and Credit columns — the thinking is up to you.' },

      { t: 'h', text: 'Contra accounts: the rebels' },
      { t: 'p', html: 'A <b>contra account</b> sits with a group but has the <i>opposite</i> normal balance, reducing its partner. They let you keep the original number visible while showing a reduction.' },
      {
        t: 'table',
        head: ['Contra account', 'Paired with', 'Normal balance'],
        rows: [
          ['Accumulated depreciation', 'Equipment / buildings (asset)', '<span class="cr">Credit</span>'],
          ['Allowance for doubtful accounts', 'Accounts receivable (asset)', '<span class="cr">Credit</span>'],
          ['Sales returns & allowances, sales discounts', 'Sales revenue', '<span class="dr">Debit</span>'],
          ['Drawings / Treasury shares', 'Equity', '<span class="dr">Debit</span>'],
          ['Discount on bonds payable', 'Bonds payable (liability)', '<span class="dr">Debit</span>'],
        ],
      },
      {
        t: 'pencil',
        html: 'Say whether each account is increased by a debit or a credit — and give its normal balance.',
        items: [
          { q: 'Accounts Payable', a: 'Liability → increases with a <b>credit</b>; normal balance credit.' },
          { q: 'Prepaid Insurance', a: 'Asset (insurance paid in advance) → increases with a <b>debit</b>; normal balance debit.' },
          { q: 'Unearned Revenue', a: 'Liability (you owe goods/services) → <b>credit</b>; normal balance credit. Tricky one — it says “revenue” but it’s a liability!' },
          { q: 'Accumulated Depreciation', a: 'Contra-asset → increases with a <b>credit</b>; normal balance credit.' },
          { q: 'Interest Income', a: 'Revenue → <b>credit</b>.' },
        ],
      },
      {
        t: 'nodumb',
        qa: [
          ['Is it bad if an asset has a credit balance?', 'Usually a red flag. Cash with a credit balance = overdraft (really a liability). A receivable with a credit balance = a customer overpaid (you owe them). It can happen, but investigate.'],
          ['Why not just use + and −?', 'Because with two sides that must always balance, the system checks itself. If debits ≠ credits, you know instantly that something is wrong. A plus/minus list has no such built-in alarm.'],
          ['Who invented this?', 'Double-entry bookkeeping was used by Italian merchants and first published by Luca Pacioli in 1494. It has survived 500+ years for a reason.'],
        ],
      },
      {
        t: 'bullets',
        items: [
          'Debit = left, credit = right. Not good or bad.',
          '<b>DEA-LER</b>: Drawings, Expenses, Assets ↑ with debits; Liabilities, Equity, Revenue ↑ with credits.',
          'Golden rules: Personal — debit receiver, credit giver. Real — debit what comes in, credit what goes out. Nominal — debit expenses/losses, credit incomes/gains.',
          'Every entry: total debits = total credits.',
          'Contra accounts reduce their partner and carry the opposite balance.',
        ],
      },
    ],
    quiz: [
      { q: 'In accounting, “debit” simply means…', o: ['Decrease', 'Bad news', 'Left side', 'Money leaving'], a: 2, e: 'Debit = left side of an account. Whether that increases or decreases depends on the account type.' },
      { q: 'Which account increases with a <b>credit</b>?', o: ['Rent expense', 'Equipment', 'Sales revenue', 'Drawings'], a: 2, e: 'Revenue increases equity, and equity increases on the credit side.' },
      { q: 'The normal balance of Accounts Receivable is…', o: ['Debit', 'Credit', 'Zero', 'Depends on the customer'], a: 0, e: 'Receivables are assets → debit balance.' },
      { q: 'Under the golden rules, a supplier’s account is a…', o: ['Real account', 'Nominal account', 'Personal account', 'Contra account'], a: 2, e: 'Suppliers are persons/organisations → personal accounts. Debit the receiver, credit the giver.' },
      { q: '“Debit what comes in, credit what goes out” applies to…', o: ['Personal accounts', 'Real accounts', 'Nominal accounts', 'All accounts'], a: 1, e: 'Real accounts are things/property.' },
      { q: 'Accumulated depreciation normally has a…', o: ['Debit balance', 'Credit balance', 'Zero balance', 'Debit or credit randomly'], a: 1, e: 'It’s a contra-asset, so it carries a credit balance that reduces the asset.' },
      { q: 'When your bank says it “credited your account”, in YOUR books you…', o: ['Credit Cash', 'Debit Cash', 'Credit Revenue only', 'Do nothing'], a: 1, e: 'The bank credits its liability to you; you debit your Cash (asset) account.' },
      { q: 'Unearned revenue is a…', o: ['Revenue', 'Asset', 'Liability', 'Expense'], a: 2, e: 'You’ve been paid but still owe the goods/service → liability, credit balance.' },
    ],
    cards: [
      ['Debit (Dr)', 'The left side of an account.'],
      ['Credit (Cr)', 'The right side of an account.'],
      ['DEA-LER', 'Drawings, Expenses, Assets increase with debits; Liabilities, Equity, Revenue increase with credits.'],
      ['Golden rule — Personal', 'Debit the receiver, credit the giver.'],
      ['Golden rule — Real', 'Debit what comes in, credit what goes out.'],
      ['Golden rule — Nominal', 'Debit all expenses and losses, credit all incomes and gains.'],
      ['Normal balance', 'The side on which an account increases; where its balance usually sits.'],
      ['Contra account', 'An account that offsets its partner and carries the opposite normal balance (e.g., accumulated depreciation).'],
    ],
  });

  /* =============================== CH 4 =============================== */
  HF.addChapter({
    id: 'journal-entries',
    part: 'p1',
    title: 'Journal Entries',
    subtitle: 'The diary of your business, written in double entry',
    art: 'journal',
    level: 'Beginner',
    minutes: 25,
    quote: 'If it isn’t in the journal, it didn’t happen.',
    goals: ['Recognise source documents', 'Analyse a transaction in five steps', 'Write simple and compound journal entries with narrations', 'Know what special journals are (and how Odoo uses journals)'],
    blocks: [
      { t: 'h', text: 'Paper trail first' },
      { t: 'p', html: 'Every entry starts with evidence — a <b>source document</b>. Auditors love them; tax inspectors demand them.' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '🧾', t: 'Sales invoice', d: 'You bill a customer → revenue and receivable.' },
          { icon: '📥', t: 'Vendor bill', d: 'A supplier bills you → expense/asset and payable.' },
          { icon: '🧾', t: 'Cash receipt / voucher', d: 'Proof cash came in or went out.' },
          { icon: '🏦', t: 'Bank statement', d: 'Fees, interest, transfers the bank recorded.' },
          { icon: '👥', t: 'Payroll sheet', d: 'Wages, deductions, employer contributions.' },
          { icon: '📝', t: 'Debit/credit note', d: 'Corrections and returns between you and a partner.' },
        ],
      },

      { t: 'h', text: 'The anatomy of a journal entry' },
      { t: 'entry', date: '2 January 2026', title: 'Journal entry #1', lines: [['Bank', 20000, 0], ['Max — Capital', 0, 20000]], narr: 'Being capital introduced by the owner' },
      {
        t: 'list',
        items: [
          '<b>Date</b> — when the transaction happened.',
          '<b>Debit line(s)</b> first, account name flush left.',
          '<b>Credit line(s)</b> indented (traditionally prefixed with “To”).',
          '<b>Amounts</b> in the debit and credit columns — totals must match.',
          '<b>Narration</b> — a short explanation (“Being…”). Future you will thank present you.',
        ],
      },

      { t: 'h', text: 'Five questions for every transaction' },
      {
        t: 'steps',
        items: [
          { t: 'What happened?', d: 'Read the source document. “Bought a laptop for $1,200, paid by bank transfer.”' },
          { t: 'Which accounts are affected?', d: 'Office Equipment and Bank.' },
          { t: 'What type is each account?', d: 'Office Equipment = asset. Bank = asset.' },
          { t: 'Up or down?', d: 'Equipment ↑, Bank ↓.' },
          { t: 'Debit or credit?', d: 'Asset ↑ → debit Equipment. Asset ↓ → credit Bank. Check: 1,200 = 1,200 ✔' },
        ],
      },
      { t: 'entry', date: '5 January 2026', lines: [['Office Equipment', 1200, 0], ['Bank', 0, 1200]], narr: 'Being laptop purchased by bank transfer' },
      { t: 'say', who: 'max', html: 'So I just ask: <i>what went up, what went down, and which side does that go on?</i> That’s it?' },
      { t: 'say', who: 'penny', right: true, html: 'That’s it. 95% of journal entries are just those five questions. The other 5% are judgement calls we’ll meet later (accruals, estimates, revenue recognition).' },

      { t: 'h', text: 'Max’s first month, in entries' },
      { t: 'entry', date: 'Jan 8', lines: [['Inventory (Bikes)', 8000, 0], ['Accounts Payable — Gear Supply Co.', 0, 8000]], narr: 'Bought 20 bikes on 30-day credit' },
      { t: 'entry', date: 'Jan 12', lines: [['Bank', 1500, 0], ['Sales Revenue', 0, 1500]], narr: 'Sold 3 bikes for cash' },
      { t: 'entry', date: 'Jan 12', lines: [['Cost of Goods Sold', 1200, 0], ['Inventory (Bikes)', 0, 1200]], narr: 'Cost of 3 bikes sold (perpetual inventory)' },
      { t: 'entry', date: 'Jan 20', lines: [['Accounts Receivable — Azure Interior', 3000, 0], ['Sales Revenue', 0, 3000]], narr: 'Sold 6 bikes on credit' },
      { t: 'entry', date: 'Jan 31', lines: [['Rent Expense', 1500, 0], ['Bank', 0, 1500]], narr: 'Paid January rent' },
      { t: 'h3', text: 'Compound entries' },
      { t: 'p', html: 'When more than two accounts are involved, write one <b>compound</b> entry. Example: Max buys a $15,000 van, paying $5,000 now and signing a loan for the rest.' },
      { t: 'entry', date: 'Jan 25', lines: [['Vehicles', 15000, 0], ['Bank', 0, 5000], ['Vehicle Loan', 0, 10000]], narr: 'Van purchased, part cash, part loan' },
      { t: 'watch', html: 'Never “force” an entry to balance by adding a random plug line. If your debits and credits don’t match, one of your five answers is wrong — go back and find it.' },

      {
        t: 'widget',
        name: 'journal',
        opts: {
          id: 'ch4-journal',
          accounts: ['Bank', 'Cash', 'Accounts Receivable', 'Inventory', 'Office Equipment', 'Vehicles', 'Accounts Payable', 'Bank Loan', 'Capital', 'Drawings', 'Sales Revenue', 'Service Revenue', 'Cost of Goods Sold', 'Rent Expense', 'Wages Expense', 'Utilities Expense', 'Interest Expense'],
          scenarios: [
            { date: 'Feb 1', text: 'Max puts another <b>$5,000</b> of his own money into the business bank account.', lines: [{ acct: 'Bank', dr: 5000 }, { acct: 'Capital', cr: 5000 }], why: 'Asset ↑ (debit) and equity ↑ (credit).' },
            { date: 'Feb 3', text: 'Paid staff wages of <b>$2,400</b> from the bank.', lines: [{ acct: 'Wages Expense', dr: 2400 }, { acct: 'Bank', cr: 2400 }], why: 'Expense ↑ debit, asset ↓ credit.' },
            { date: 'Feb 6', text: 'Repaired a customer’s bike for <b>$300</b>; they’ll pay next week.', lines: [{ acct: 'Accounts Receivable', dr: 300 }, { acct: 'Service Revenue', cr: 300 }], why: 'Revenue is earned now (accrual!), and the customer owes you.' },
            { date: 'Feb 10', text: 'Bought a printer for <b>$450</b> on credit from an office supplier.', lines: [{ acct: 'Office Equipment', dr: 450 }, { acct: 'Accounts Payable', cr: 450 }], why: 'Asset ↑, liability ↑.' },
            { date: 'Feb 13', text: 'The customer from Feb 6 pays the <b>$300</b> into the bank.', lines: [{ acct: 'Bank', dr: 300 }, { acct: 'Accounts Receivable', cr: 300 }], why: 'No new revenue — the receivable turns into cash.', hint: 'Was revenue already recorded on Feb 6?' },
            { date: 'Feb 20', text: 'Paid the loan instalment: <b>$1,000</b> principal plus <b>$80</b> interest.', lines: [{ acct: 'Bank Loan', dr: 1000 }, { acct: 'Interest Expense', dr: 80 }, { acct: 'Bank', cr: 1080 }], why: 'Principal reduces the liability; interest is an expense. A compound entry!', hint: 'Only the interest is an expense.' },
            { date: 'Feb 28', text: 'Max withdraws <b>$700</b> cash for personal use.', lines: [{ acct: 'Drawings', dr: 700 }, { acct: 'Cash', cr: 700 }], why: 'Drawings reduce equity (debit). Not an expense!' },
          ],
        },
      },

      { t: 'h', text: 'Special journals (and Odoo’s journals)' },
      { t: 'p', html: 'Writing every entry in one giant book gets messy. So businesses split the journal by type of transaction:' },
      {
        t: 'table',
        head: ['Journal', 'Used for', 'Odoo journal type'],
        rows: [
          ['Sales journal', 'Credit sales / customer invoices', '<b>Sales</b> (e.g., INV)'],
          ['Purchases journal', 'Credit purchases / vendor bills', '<b>Purchase</b> (e.g., BILL)'],
          ['Cash receipts & payments journals', 'Money in / money out', '<b>Bank</b> and <b>Cash</b> (e.g., BNK1, CSH1)'],
          ['General journal', 'Everything else: adjustments, depreciation, corrections, opening balances', '<b>Miscellaneous</b> (e.g., MISC)'],
        ],
      },
      { t: 'odoo', title: 'Odoo writes journal entries for you', path: 'Accounting > Accounting > Journal Entries', html: 'In Odoo, every posted invoice, bill and payment <b>is</b> a journal entry (<code>account.move</code>) with journal items (<code>account.move.line</code>). You only create manual entries for things like accruals, depreciation adjustments or corrections — in the <b>Miscellaneous Operations</b> journal. Odoo refuses to post an entry whose debits and credits don’t balance.' },
      {
        t: 'nodumb',
        qa: [
          ['What’s the difference between the journal and the ledger?', 'The journal is <b>chronological</b> (by date). The ledger is <b>by account</b> (all cash movements together). You record in the journal first, then post to the ledger. Next chapter!'],
          ['Do I need a narration for every entry?', 'Strongly recommended. In Odoo, the reference/label fields do this job. Auditors will ask “why?” about anything unusual.'],
          ['Can an entry have three debits and one credit?', 'Yes — any combination, as long as total debits = total credits.'],
        ],
      },
      {
        t: 'bullets',
        items: [
          'Every entry is backed by a source document.',
          'Format: date, debit lines, credit lines, amounts, narration.',
          'Five questions: what happened, which accounts, what type, up or down, debit or credit.',
          'Compound entries have more than two lines but still balance.',
          'Special journals group similar transactions; Odoo uses Sales, Purchase, Bank, Cash and Miscellaneous journals.',
        ],
      },
    ],
    quiz: [
      { q: 'A journal records transactions…', o: ['By account', 'In chronological order', 'Only at year-end', 'Only for cash'], a: 1, e: 'The journal is the book of original entry, in date order.' },
      { q: 'Bought inventory on credit for $2,000. The entry is…', o: ['Dr Inventory / Cr Bank', 'Dr Payables / Cr Inventory', 'Dr Inventory / Cr Accounts Payable', 'Dr Purchases expense / Cr Revenue'], a: 2, e: 'Inventory (asset) up, payables (liability) up.' },
      { q: 'A customer pays an invoice you issued last month. You…', o: ['Dr Bank / Cr Sales Revenue', 'Dr Bank / Cr Accounts Receivable', 'Dr Accounts Receivable / Cr Bank', 'Dr Sales / Cr Bank'], a: 1, e: 'Revenue was recorded when invoiced; now the receivable becomes cash.' },
      { q: 'Loan repayment of $1,000 principal + $100 interest. Which line is WRONG?', o: ['Dr Bank Loan 1,000', 'Dr Interest Expense 100', 'Cr Bank 1,100', 'Dr Bank Loan 1,100'], a: 3, e: 'Only the principal reduces the loan; the interest is an expense.' },
      { q: 'An entry with more than two accounts is called…', o: ['A reversing entry', 'A compound entry', 'A closing entry', 'A contra entry'], a: 1, e: 'Compound entries involve three or more accounts.' },
      { q: 'In Odoo, a manual depreciation adjustment would normally go in which journal type?', o: ['Sales', 'Bank', 'Miscellaneous', 'Purchase'], a: 2, e: 'Adjustments and non-routine entries go to Miscellaneous Operations.' },
      { q: 'Which is NOT a source document?', o: ['Vendor bill', 'Bank statement', 'Trial balance', 'Sales invoice'], a: 2, e: 'A trial balance is a report produced from the ledger, not evidence of a transaction.' },
    ],
    cards: [
      ['Journal', 'Book of original entry; records transactions chronologically.'],
      ['Source document', 'Evidence of a transaction: invoice, bill, receipt, bank statement, payroll.'],
      ['Narration', 'A brief explanation written under a journal entry.'],
      ['Compound entry', 'A journal entry with three or more accounts.'],
      ['Special journals', 'Separate journals for sales, purchases, cash receipts, cash payments; others go to the general journal.'],
      ['Odoo journal types', 'Sales, Purchase, Bank, Cash, (Credit Card), Miscellaneous.'],
    ],
  });

  /* =============================== CH 5 =============================== */
  HF.addChapter({
    id: 'ledger',
    part: 'p1',
    title: 'Ledgers & T-Accounts',
    subtitle: 'From a diary to a filing cabinet',
    art: 'ledger',
    level: 'Beginner',
    minutes: 20,
    quote: 'The journal tells the story. The ledger tells you where you stand.',
    goals: ['Post journal entries to ledger accounts', 'Use T-accounts and compute balances', 'Balance off an account (c/d and b/d)', 'Explain control accounts, subsidiary ledgers and the chart of accounts'],
    blocks: [
      { t: 'h', text: 'Why we need a ledger' },
      { t: 'p', html: 'Max asks: <i>“How much cash do I have right now?”</i> With only a journal, you’d have to read every entry since January and add up the cash lines. Painful. The <b>ledger</b> solves this by keeping one page (one account) for each item: all cash movements together, all sales together, and so on.' },
      { t: 'flow', items: [{ t: '🧾 Source document', c: '#fff3a8' }, { t: '📓 Journal<br><small>by date</small>', c: '#bfe0f2' }, { t: '📚 Ledger<br><small>by account</small>', c: '#b5e3c4' }, { t: '⚖️ Trial balance', c: '#f7c6d0' }, { t: '📊 Statements', c: '#d9c7f0' }] },
      { t: 'p', html: 'Copying each journal line to its ledger account is called <b>posting</b>. A debit in the journal is posted to the debit side of the account; a credit to the credit side. That’s all.' },

      { t: 'h', text: 'Your turn: post to T-accounts' },
      {
        t: 'widget',
        name: 'taccount',
        opts: {
          id: 'ch5-t',
          accounts: ['Cash', 'Inventory', 'Accounts Payable', 'Capital', 'Sales', 'Rent Expense'],
          txs: [
            { text: 'Owner invests cash', dr: 'Cash', cr: 'Capital', amt: 10000, why: 'Cash ↑ debit; Capital ↑ credit.' },
            { text: 'Buy inventory on credit', dr: 'Inventory', cr: 'Accounts Payable', amt: 4000, why: 'Asset ↑ debit; liability ↑ credit.' },
            { text: 'Cash sale', dr: 'Cash', cr: 'Sales', amt: 2500, why: 'Cash ↑ debit; revenue ↑ credit.' },
            { text: 'Pay rent', dr: 'Rent Expense', cr: 'Cash', amt: 900, why: 'Expense ↑ debit; cash ↓ credit.' },
            { text: 'Pay part of supplier bill', dr: 'Accounts Payable', cr: 'Cash', amt: 1500, why: 'Liability ↓ debit; cash ↓ credit.' },
          ],
          done: 'Cash ends at 10,000 + 2,500 − 900 − 1,500 = <b>10,100 Dr</b>.',
        },
      },

      { t: 'h', text: 'Running-balance ledger format' },
      { t: 'p', html: 'T-accounts are great for learning. Real ledgers (and Odoo’s <b>General Ledger</b> report) use a running-balance format:' },
      {
        t: 'table',
        caption: 'Cash account',
        head: ['Date', 'Description', 'Ref', 'Debit', 'Credit', 'Balance'],
        rows: [
          ['Jan 2', 'Capital introduced', 'J1', '10,000', '', '10,000 Dr'],
          ['Jan 12', 'Cash sale', 'J3', '2,500', '', '12,500 Dr'],
          ['Jan 31', 'Rent', 'J4', '', '900', '11,600 Dr'],
          ['Jan 31', 'Paid Gear Supply Co.', 'J5', '', '1,500', '10,100 Dr'],
        ],
      },
      { t: 'p', html: 'The <b>Ref</b> (posting reference) links back to the journal, creating an <b>audit trail</b> you can follow in both directions.' },

      { t: 'h', text: 'Balancing off an account' },
      { t: 'p', html: 'At period end, traditional manual books “close off” each account: add both sides, put the difference on the smaller side as <b>Balance c/d</b> (carried down) so both sides total the same, then bring it down on the opposite side as <b>Balance b/d</b> (brought down) to start the next period.' },
      {
        t: 'table',
        caption: 'Cash A/c (traditional format)',
        head: ['Dr', '', 'Cr', ''],
        rows: [
          ['To Capital', '10,000', 'By Rent', '900'],
          ['To Sales', '2,500', 'By Accounts Payable', '1,500'],
          ['', '', '<b>By Balance c/d</b>', '<b>10,100</b>'],
          { _cls: 'tot', cells: ['', '12,500', '', '12,500'] },
          ['<b>To Balance b/d</b>', '<b>10,100</b>', '', ''],
        ],
      },

      { t: 'h', text: 'Control accounts & subsidiary ledgers' },
      { t: 'p', html: 'Max has 200 customers. Should the general ledger have 200 receivable accounts? No — it has <b>one</b> Accounts Receivable <b>control account</b>. The detail per customer lives in a <b>subsidiary ledger</b> (the sales/receivables ledger). Same for suppliers.' },
      {
        t: 'compare',
        cols: [
          { t: 'General ledger', color: 'blue', items: ['Accounts Receivable (control): <b>$18,400</b>', 'Accounts Payable (control): <b>$9,200</b>'] },
          { t: 'Subsidiary ledgers', color: 'yellow', items: ['Azure Interior $6,000', 'Deco Addict $7,400', 'Ready Mat $5,000', '= $18,400 ✔ must equal the control account'] },
        ],
      },
      { t: 'odoo', title: 'In Odoo: partners instead of sub-ledgers', path: 'Accounting > Reporting > Partner Ledger', html: 'Odoo uses a single <b>Receivable</b> account (e.g., 121000) and a single <b>Payable</b> account (e.g., 211000). Each journal item carries a <b>partner</b>, so the <b>Partner Ledger</b> and <b>Aged Receivable/Payable</b> reports are your subsidiary ledgers — automatically consistent with the control account.' },

      { t: 'h', text: 'The chart of accounts' },
      { t: 'p', html: 'The <b>chart of accounts</b> (CoA) is the list of every account the business uses, usually numbered by type. A common pattern:' },
      {
        t: 'table',
        head: ['Range', 'Type', 'Examples'],
        rows: [
          ['1xxx', 'Assets', '1000 Cash · 1100 Bank · 1200 Receivables · 1300 Inventory · 1500 Equipment'],
          ['2xxx', 'Liabilities', '2000 Payables · 2100 VAT/GST payable · 2300 Loans'],
          ['3xxx', 'Equity', '3000 Capital · 3100 Retained earnings · 3200 Drawings'],
          ['4xxx', 'Revenue', '4000 Sales · 4100 Service revenue · 4900 Other income'],
          ['5xxx–6xxx', 'Expenses', '5000 COGS · 6000 Rent · 6100 Wages · 6200 Utilities'],
        ],
      },
      { t: 'sticky', html: 'Tip: leave gaps in your numbering (1000, 1010, 1020…) so you can add accounts later without renumbering.' },
      { t: 'odoo', html: 'When you install a <b>fiscal localization package</b> (e.g., US, India, Belgium, Saudi Arabia…), Odoo loads a country-specific chart of accounts and taxes. Each account has an <b>account type</b> (Receivable, Bank and Cash, Current Assets, Fixed Assets, Current Liabilities, Equity, Income, Expenses, Cost of Revenue, etc.) that decides where it appears on the reports.' },
      {
        t: 'nodumb',
        qa: [
          ['Do I post every journal line separately?', 'Yes — each line goes to its own account. Software does it instantly the moment you post.'],
          ['What if the subsidiary ledger doesn’t match the control account?', 'Something was posted to one but not the other (e.g., a manual entry to Receivables without a partner). Find and fix it before closing the period.'],
        ],
      },
      { t: 'bullets', items: ['Posting = copying journal lines to ledger accounts.', 'T-accounts: debits left, credits right; balance = difference.', 'Balance c/d and b/d carry balances between periods.', 'Control accounts summarise subsidiary ledgers (customers, suppliers).', 'The chart of accounts lists and numbers all accounts by type.'] },
    ],
    quiz: [
      { q: 'Transferring journal entries to ledger accounts is called…', o: ['Balancing', 'Posting', 'Closing', 'Reconciling'], a: 1, e: 'Posting moves each line to its ledger account.' },
      { q: 'Cash: debits 12,500, credits 2,400. The balance is…', o: ['10,100 Cr', '14,900 Dr', '10,100 Dr', '12,500 Dr'], a: 2, e: '12,500 − 2,400 = 10,100 on the debit side.' },
      { q: 'A control account…', o: ['Lists every customer separately', 'Summarises a subsidiary ledger in the GL', 'Is used only for cash', 'Is a contra account'], a: 1, e: 'E.g., Accounts Receivable control = total of all customer balances.' },
      { q: '“Balance b/d” means…', o: ['Balance brought down to start the next period', 'Bad debt', 'Balance before depreciation', 'Bank deposit'], a: 0, e: 'b/d = brought down; c/d = carried down.' },
      { q: 'In a typical chart of accounts, 4xxx accounts are…', o: ['Assets', 'Liabilities', 'Revenue', 'Expenses'], a: 2, e: 'A common convention: 1 assets, 2 liabilities, 3 equity, 4 revenue, 5–6 expenses.' },
      { q: 'In Odoo, which report acts as the customer subsidiary ledger?', o: ['General Ledger', 'Partner Ledger', 'Tax Report', 'Balance Sheet'], a: 1, e: 'The Partner Ledger breaks receivable/payable balances down per partner.' },
    ],
    cards: [
      ['Ledger', 'Collection of all accounts, each showing every movement and the balance.'],
      ['Posting', 'Transferring journal lines to the ledger accounts.'],
      ['T-account', 'Simplified ledger account: name on top, debits left, credits right.'],
      ['Control account', 'A GL account summarising a subsidiary ledger (e.g., Receivables).'],
      ['Chart of accounts', 'Numbered list of all accounts used by a business.'],
      ['Balance c/d / b/d', 'Carried down (closing) / brought down (opening next period).'],
    ],
  });

  /* =============================== CH 6 =============================== */
  HF.addChapter({
    id: 'trial-balance',
    part: 'p1',
    title: 'The Trial Balance',
    subtitle: 'Your first sanity check — and the errors it can’t see',
    art: 'scale',
    level: 'Beginner',
    minutes: 20,
    quote: 'A trial balance that balances proves the arithmetic. It doesn’t prove you’re right.',
    goals: ['Prepare a trial balance from ledger balances', 'List errors a trial balance reveals and ones it doesn’t', 'Use a suspense account and write correcting entries'],
    blocks: [
      { t: 'h', text: 'What is a trial balance?' },
      { t: 'p', html: 'A <b>trial balance</b> (TB) is a list of every ledger account with its balance in either the debit or credit column. Because every entry had equal debits and credits, the two columns must have equal totals.' },
      {
        t: 'widget',
        name: 'sort',
        opts: {
          id: 'ch6-tb',
          title: 'Build Max’s trial balance',
          sub: 'Drop each balance into the correct column. Watch the totals — they should match at the end!',
          totals: true,
          bins: [
            { id: 'D', label: 'DEBIT balances', color: '#2e86ab' },
            { id: 'C', label: 'CREDIT balances', color: '#e4572e' },
          ],
          items: [
            { text: 'Cash', amt: 10100, bin: 'D', why: 'Asset.' },
            { text: 'Accounts Receivable', amt: 3000, bin: 'D', why: 'Asset.' },
            { text: 'Inventory', amt: 6800, bin: 'D', why: 'Asset.' },
            { text: 'Van', amt: 15000, bin: 'D', why: 'Asset.' },
            { text: 'Accounts Payable', amt: 6500, bin: 'C', why: 'Liability.' },
            { text: 'Vehicle Loan', amt: 10000, bin: 'C', why: 'Liability.' },
            { text: 'Capital', amt: 20000, bin: 'C', why: 'Equity.' },
            { text: 'Sales Revenue', amt: 4500, bin: 'C', why: 'Revenue.' },
            { text: 'Cost of Goods Sold', amt: 1200, bin: 'D', why: 'Expense.' },
            { text: 'Rent Expense', amt: 1500, bin: 'D', why: 'Expense.' },
            { text: 'Wages Expense', amt: 2400, bin: 'D', why: 'Expense.' },
            { text: 'Drawings', amt: 1000, bin: 'D', why: 'Drawings have a debit balance.' },
          ],
          done: 'Both columns total <b>$41,000</b>.',
        },
      },
      { t: 'odoo', path: 'Accounting > Reporting > Trial Balance', html: 'Odoo produces the trial balance live from posted entries, with opening balance, period movements and closing balance columns. Since Odoo won’t post an unbalanced entry, the TB always balances — so the interesting question becomes <b>“is anything in the wrong account?”</b>' },

      { t: 'h', text: 'Errors the TB catches' },
      {
        t: 'cards',
        cols: 3,
        items: [
          { icon: '1️⃣', t: 'Single-sided posting', d: 'Debit posted, credit forgotten. Columns differ by the amount.', color: 'red' },
          { icon: '🔀', t: 'Transposition', d: 'Wrote 540 instead of 450 on one side. The difference (90) is always divisible by <b>9</b>.', color: 'red' },
          { icon: '➕', t: 'Casting (addition) error', d: 'Added up a ledger column wrong.', color: 'red' },
          { icon: '↔️', t: 'Wrong-side balance', d: 'A debit balance listed in the credit column → difference = 2× the amount.', color: 'red' },
          { icon: '🔢', t: 'Unequal amounts', d: 'Dr 500, Cr 50 in the same entry.', color: 'red' },
        ],
      },
      { t: 'sticky', side: 'right', color: 'blue', html: '<b>The rule of 9:</b> if your TB is off by a number divisible by 9 (like 90, 180, 2,700), look for swapped digits!' },
      { t: 'h', text: 'Errors the TB can’t catch' },
      { t: 'p', html: 'These errors leave debits equal to credits, so the TB still balances. Sneaky! Remember them with <b>“CROPC”</b> or just learn the list:' },
      {
        t: 'widget',
        name: 'match',
        opts: {
          id: 'ch6-errors',
          title: 'Name that error',
          pairs: [
            ['Omission', 'Transaction never recorded at all (e.g., a lost invoice).'],
            ['Commission', 'Right type of account, wrong account (e.g., posted to customer A instead of customer B).'],
            ['Principle', 'Wrong type of account (e.g., van purchase debited to Repairs Expense).'],
            ['Original entry', 'Wrong amount on the source document, recorded consistently on both sides.'],
            ['Complete reversal', 'Correct accounts, but debit and credit swapped.'],
            ['Compensating', 'Two errors that cancel each other out.'],
          ],
        },
      },

      { t: 'h', text: 'Suspense accounts & corrections' },
      { t: 'p', html: 'If the TB doesn’t balance and you need to draft statements anyway, park the difference in a temporary <b>suspense account</b>. Then find each error and clear it with a correcting entry.' },
      { t: 'p', html: '<b>Example:</b> TB debits are $200 less than credits because $200 of rent was credited to Bank but never debited to Rent Expense. Suspense gets a debit of $200 to make the TB balance. Correction:' },
      { t: 'entry', lines: [['Rent Expense', 200, 0], ['Suspense', 0, 200]], narr: 'Correcting rent not posted to the expense account' },
      { t: 'p', html: '<b>Example (error of principle):</b> a $3,000 laptop was debited to Office Expenses. No suspense needed, just reclassify:' },
      { t: 'entry', lines: [['Office Equipment', 3000, 0], ['Office Expenses', 0, 3000]], narr: 'Reclassifying laptop to fixed assets' },
      { t: 'odoo', html: 'Odoo has a <b>Bank Suspense Account</b> (e.g., 101402). It holds bank statement lines that haven’t been reconciled yet. It’s the same idea: a temporary parking place that must be cleared.' },
      {
        t: 'pencil',
        html: 'Will the trial balance still balance?',
        items: [
          { q: 'A $750 credit sale to Deco Addict was posted to Azure Interior’s account.', a: 'Yes, it balances — error of <b>commission</b>.' },
          { q: 'A $300 cash purchase was posted as Dr Purchases $300 / Cr Cash $30.', a: 'No — unequal amounts; TB is out by $270.' },
          { q: 'A $90 payment was recorded as Dr Cash / Cr Utilities instead of Dr Utilities / Cr Cash.', a: 'Yes — <b>complete reversal</b>. To fix: Dr Utilities $180 / Cr Cash $180 (2× the amount), or reverse and re-post.' },
          { q: 'The Sales column total was added as $14,600 instead of $16,400.', a: 'No — casting/transposition error of $1,800 (divisible by 9!).' },
        ],
      },
      { t: 'bullets', items: ['A trial balance lists all ledger balances in debit and credit columns.', 'Equal totals prove arithmetic accuracy, not correctness.', 'Revealed: single-sided, transposition, casting, unequal amounts, wrong-side balances.', 'Not revealed: omission, commission, principle, original entry, complete reversal, compensating.', 'Suspense accounts temporarily hold differences until errors are corrected.'] },
    ],
    quiz: [
      { q: 'A balanced trial balance proves that…', o: ['There are no errors', 'Debits equal credits', 'Profit is correct', 'Cash is correct'], a: 1, e: 'It only proves arithmetic equality of debits and credits.' },
      { q: 'Posting a van purchase to Repairs Expense is an error of…', o: ['Commission', 'Principle', 'Omission', 'Original entry'], a: 1, e: 'Wrong class of account (asset vs expense) → error of principle.' },
      { q: 'The TB is out by $360. A likely cause is…', o: ['Omission', 'Transposed digits', 'Compensating error', 'Complete reversal'], a: 1, e: '360 is divisible by 9 — classic transposition sign.' },
      { q: 'Which error would the TB reveal?', o: ['Entry recorded in the wrong customer account', 'Transaction entirely omitted', 'Debit posted but credit forgotten', 'Debit and credit swapped'], a: 2, e: 'A single-sided posting makes the columns unequal.' },
      { q: 'A suspense account is used to…', o: ['Record suspicious customers', 'Hold a TB difference temporarily', 'Store prepaid expenses', 'Record owner drawings'], a: 1, e: 'It parks the difference until errors are found and corrected.' },
      { q: 'Dr Cash / Cr Rent was recorded for a $500 rent payment. To correct with one entry:', o: ['Dr Rent 500 / Cr Cash 500', 'Dr Rent 1,000 / Cr Cash 1,000', 'Dr Cash 500 / Cr Rent 500', 'No correction needed'], a: 1, e: 'Undo the wrong entry (500) and record the right one (500) → double the amount.' },
    ],
    cards: [
      ['Trial balance', 'List of all ledger balances; total debits should equal total credits.'],
      ['Error of commission', 'Correct type of account, wrong specific account.'],
      ['Error of principle', 'Wrong type/class of account (e.g., capital vs revenue expenditure).'],
      ['Error of omission', 'Transaction not recorded at all.'],
      ['Complete reversal', 'Correct accounts and amount, but debit and credit swapped.'],
      ['Suspense account', 'Temporary account holding a TB difference until corrected.'],
      ['Rule of 9', 'A difference divisible by 9 suggests a transposition error.'],
    ],
  });

  /* =============================== CH 7 =============================== */
  HF.addChapter({
    id: 'accounting-cycle',
    part: 'p1',
    title: 'The Accounting Cycle',
    subtitle: 'Round and round: from transaction to financial statements, every period',
    art: 'cycle',
    level: 'Beginner',
    minutes: 15,
    quote: 'Every month, every quarter, every year — the same dance. Learn the steps once and you can dance forever.',
    goals: ['List the steps of the accounting cycle in order', 'Explain what happens during, and at the end of, a period', 'Understand month-end close as the modern version of the cycle'],
    blocks: [
      { t: 'h', text: 'The steps' },
      {
        t: 'widget',
        name: 'cycle',
        opts: {
          id: 'ch7-cycle',
          center: 'Accounting Cycle',
          steps: [
            { t: 'Identify & analyse transactions', d: 'Collect source documents and decide which accounts are affected and how.', ex: 'Max sells a bike — invoice #0042.' },
            { t: 'Journalise', d: 'Record each transaction in the journal with equal debits and credits.', ex: 'Dr Receivables 500 / Cr Sales 500.' },
            { t: 'Post to the ledger', d: 'Transfer journal lines to their ledger accounts.', ex: 'Receivables account now shows +500.' },
            { t: 'Unadjusted trial balance', d: 'List ledger balances; check debits = credits.', ex: 'Totals $41,000 / $41,000.' },
            { t: 'Adjusting entries', d: 'Record accruals, deferrals, depreciation and estimates so the period is complete and accurate.', ex: 'Accrue $300 of electricity used but not yet billed.' },
            { t: 'Adjusted trial balance', d: 'A new TB including adjustments — the basis for statements.', ex: 'Utilities now 1,100 instead of 800.' },
            { t: 'Prepare financial statements', d: 'Income statement → statement of changes in equity → balance sheet → cash flow statement.', ex: 'Net profit $2,100 for January.' },
            { t: 'Closing entries', d: 'Zero out revenue, expense and drawings into retained earnings/capital so the next period starts fresh.', ex: 'Close Sales and expenses to Income Summary → Retained Earnings.' },
            { t: 'Post-closing trial balance', d: 'Only balance sheet (permanent) accounts remain.', ex: 'Assets, liabilities and equity only.' },
            { t: 'Reversing entries (optional)', d: 'On day 1 of the next period, reverse certain accruals to simplify later recording.', ex: 'Reverse the $300 electricity accrual; record the real bill normally.' },
          ],
        },
      },
      { t: 'p', html: 'Steps 1–3 happen <b>every day</b> during the period. Steps 4–10 happen at <b>period end</b> — the famous “month-end close” or “year-end close”.' },

      { t: 'h', text: 'Temporary vs permanent accounts' },
      {
        t: 'compare',
        cols: [
          { t: 'Temporary (nominal)', color: 'yellow', items: ['Revenue', 'Expenses', 'Drawings / dividends', 'Income summary', '→ reset to zero each period'] },
          { t: 'Permanent (real)', color: 'blue', items: ['Assets', 'Liabilities', 'Equity (capital, retained earnings)', '→ balances carry forward forever'] },
        ],
      },
      { t: 'say', who: 'sam', html: 'Why reset revenue to zero? Didn’t we earn it?' },
      { t: 'say', who: 'penny', right: true, html: 'We did — and we keep it, inside <b>retained earnings</b>. Revenue and expenses are like a scoreboard for one game. After the game, the score goes into the season total (equity), and the scoreboard resets for the next game.' },

      { t: 'h', text: 'The modern month-end close' },
      { t: 'p', html: 'With software, journalising and posting happen automatically. Modern closing focuses on <b>completeness, accuracy and review</b>:' },
      {
        t: 'steps',
        items: [
          { t: 'Cut-off', d: 'Make sure all sales/purchases belong in the right period. Delivered on the 31st? It’s this month.' },
          { t: 'Reconcile', d: 'Bank, receivables, payables, inventory, intercompany. Every balance sheet account should be explainable.' },
          { t: 'Adjust', d: 'Accruals, prepayments, depreciation, deferred revenue, provisions, FX revaluation.' },
          { t: 'Review', d: 'Compare to budget and last month; investigate odd swings (analytical review).' },
          { t: 'Report & lock', d: 'Publish statements, file taxes, then lock the period so nobody changes it.' },
        ],
      },
      { t: 'odoo', title: 'Closing in Odoo', path: 'Accounting > Accounting > Lock Dates', html: 'Odoo doesn’t need traditional closing entries: the P&L accounts are summed into <b>Current Year Earnings</b> automatically on the balance sheet, and at year-end the result rolls into <b>undistributed / retained earnings</b>. What you <i>do</i> need: reconciliations, adjusting entries, the tax return closing entry, and <b>lock dates</b> to freeze closed periods. See Chapter 32.' },
      { t: 'brain', html: 'Why might a company that closes its books in <b>3 days</b> have an advantage over one that takes <b>3 weeks</b>? Think about decisions, problems spotted and staff time.' },
      { t: 'bullets', items: ['The cycle: identify → journalise → post → TB → adjust → adjusted TB → statements → close → post-closing TB → (reverse).', 'Temporary accounts (revenue, expenses, drawings) reset each period.', 'Permanent accounts (assets, liabilities, equity) carry forward.', 'Modern close = cut-off, reconcile, adjust, review, report & lock.'] },
    ],
    quiz: [
      { q: 'Which comes immediately after posting to the ledger?', o: ['Adjusting entries', 'Unadjusted trial balance', 'Closing entries', 'Financial statements'], a: 1, e: 'Post, then prepare the unadjusted TB to check balances.' },
      { q: 'Financial statements are prepared from the…', o: ['Unadjusted trial balance', 'Adjusted trial balance', 'Post-closing trial balance', 'Journal'], a: 1, e: 'Adjustments must be included first.' },
      { q: 'Which account is temporary?', o: ['Accounts Receivable', 'Retained Earnings', 'Rent Expense', 'Bank Loan'], a: 2, e: 'Expenses are closed at period end.' },
      { q: 'The post-closing trial balance contains…', o: ['Only revenue and expenses', 'Only balance sheet accounts', 'All accounts', 'Only cash'], a: 1, e: 'Temporary accounts are zero after closing.' },
      { q: 'Reversing entries are…', o: ['Mandatory', 'Optional, made at the start of the next period', 'Used to correct errors only', 'Closing entries'], a: 1, e: 'They simplify recording of accruals when the actual transaction occurs.' },
      { q: 'In Odoo, how does the year’s profit reach equity?', o: ['You must post manual closing entries for every account', 'It is computed automatically as current year earnings and rolled into retained/undistributed earnings', 'It stays in revenue forever', 'Through the bank journal'], a: 1, e: 'Odoo computes it on the fly; lock dates protect closed periods.' },
    ],
    cards: [
      ['Accounting cycle', 'Identify, journalise, post, TB, adjust, adjusted TB, statements, close, post-closing TB, (reverse).'],
      ['Temporary accounts', 'Revenue, expense, drawings/dividends accounts closed at period end.'],
      ['Permanent accounts', 'Asset, liability and equity accounts that carry balances forward.'],
      ['Cut-off', 'Ensuring transactions are recorded in the correct period.'],
      ['Lock date', 'A date before which entries cannot be posted or changed (in Odoo and other ERPs).'],
    ],
  });
})();
